-- =====================================================
-- SISTEMA DE GESTIÓN AIR
-- Sprint 2 y 3

-- Motor: Supabase / PostgreSQL
-- Issues integrados: 0, 9, 10, 14, 15
-- 7, 5, 11
-- =====================================================

-- =====================================================
-- 0. LIMPIEZA PARA EJECUTAR EN ENTORNO LIMPIO
-- =====================================================

DROP VIEW IF EXISTS v_historial_nombramientos CASCADE;

DROP TABLE IF EXISTS reforma_aplicada CASCADE;
DROP TABLE IF EXISTS nombramiento CASCADE;
DROP TABLE IF EXISTS elemento_normativo CASCADE;
DROP TABLE IF EXISTS reglamento CASCADE;
DROP TABLE IF EXISTS sys_log_auditoria CASCADE;
DROP TABLE IF EXISTS sys_rol_permiso CASCADE;
DROP TABLE IF EXISTS sys_usuario_rol CASCADE;
DROP TABLE IF EXISTS sys_permiso CASCADE;
DROP TABLE IF EXISTS sys_rol CASCADE;
DROP TABLE IF EXISTS sys_usuario CASCADE;
DROP TABLE IF EXISTS bitacora_asambleistas CASCADE;
DROP TABLE IF EXISTS asambleista CASCADE;
DROP TABLE IF EXISTS catalogo_tipo_reforma CASCADE;
DROP TABLE IF EXISTS catalogo_estado_vigencia CASCADE;
DROP TABLE IF EXISTS catalogo_nivel_reglamento CASCADE;
DROP TABLE IF EXISTS catalogo_puestos CASCADE;
DROP TABLE IF EXISTS catalogo_sector CASCADE;

DROP FUNCTION IF EXISTS fn_auditoria_general() CASCADE;
DROP FUNCTION IF EXISTS fn_versionar_elemento_normativo() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_traslape_nombramiento() CASCADE;
DROP FUNCTION IF EXISTS fn_bitacora_asambleista() CASCADE;

DROP VIEW IF EXISTS v_estado_quorum_sesion CASCADE;
DROP VIEW IF EXISTS v_informes_comision_certificacion CASCADE;
DROP VIEW IF EXISTS v_asistencia_comision CASCADE;
DROP VIEW IF EXISTS v_integrantes_comision CASCADE;
DROP VIEW IF EXISTS v_proponentes_propuesta CASCADE;

DROP TABLE IF EXISTS votacion CASCADE;
DROP TABLE IF EXISTS asistencia_sesion_plenaria CASCADE;
DROP TABLE IF EXISTS acta CASCADE;
DROP TABLE IF EXISTS sesion CASCADE;

DROP TABLE IF EXISTS asistencia_sesion_comision CASCADE;
DROP TABLE IF EXISTS justificaciones_por_informe CASCADE;
DROP TABLE IF EXISTS justificacion_legal CASCADE;
DROP TABLE IF EXISTS informe_directorio CASCADE;
DROP TABLE IF EXISTS punto_agenda_sesion_comision CASCADE;
DROP TABLE IF EXISTS sesion_comision CASCADE;
DROP TABLE IF EXISTS bitacora_integrante_comision CASCADE;
DROP TABLE IF EXISTS integrante_comision CASCADE;
DROP TABLE IF EXISTS proposito_comision CASCADE;
DROP TABLE IF EXISTS comision CASCADE;
DROP TABLE IF EXISTS proponente_propuesta CASCADE;
DROP TABLE IF EXISTS propuesta CASCADE;

DROP TABLE IF EXISTS catalogo_tipo_sesion CASCADE;
DROP TABLE IF EXISTS catalogo_tipo_modalidad CASCADE;
DROP TABLE IF EXISTS catalogo_estado_asistencia CASCADE;
DROP TABLE IF EXISTS catalogo_tipo_tramite CASCADE;
DROP TABLE IF EXISTS catalogo_rol_comision CASCADE;
DROP TABLE IF EXISTS catalogo_tipo_comision CASCADE;
DROP TABLE IF EXISTS catalogo_tipo_propuesta CASCADE;
DROP TABLE IF EXISTS catalogo_estado_propuesta CASCADE;

DROP VIEW IF EXISTS v_memoria_votacion_sesion CASCADE;

DROP TABLE IF EXISTS bitacora_estado_votacion CASCADE;
DROP TABLE IF EXISTS punto_agenda_sesion CASCADE;

-- =====================================================
-- 1. CATÁLOGOS COMPARTIDOS
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_sector (
    id_sector INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalogo_puestos (
    id_puesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_puesto VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalogo_nivel_reglamento (
    id_nivel_reglamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    orden INTEGER NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_nivel_orden_positivo CHECK (orden > 0)
);

CREATE TABLE IF NOT EXISTS catalogo_estado_vigencia (
    id_estado_vigencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_reforma (
    id_tipo_reforma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);

-- Catálogos Nuevos (Sprint 3):

CREATE TABLE IF NOT EXISTS catalogo_estado_propuesta (
    id_estado_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_estado_propuesta_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_propuesta (
    id_tipo_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    leyenda_legal TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_tipo_propuesta_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_comision (
    id_tipo_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_tipo_comision_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_rol_comision (
    id_rol_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_rol_comision_no_vacio CHECK (BTRIM(nombre_rol) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_tramite (
    id_tipo_tramite INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_tipo_tramite_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_estado_asistencia (
    id_estado_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_estado_asistencia_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_sesion (
    id_tipo_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    quorum_porcentaje NUMERIC(5,2) NOT NULL DEFAULT 50.00,
    requiere_mayoria_calificada BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_quorum_porcentaje
        CHECK (quorum_porcentaje > 0 AND quorum_porcentaje <= 100),

    CONSTRAINT chk_nombre_tipo_sesion_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_modalidad (
    id_tipo_modalidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_nombre_modalidad_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

-- =====================================================
-- 2. ASAMBLEÍSTAS - ISSUE #9
-- =====================================================

CREATE TABLE asambleista (
    id_asambleista INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(11) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    correo_institucional VARCHAR(150),

    CONSTRAINT chk_cedula_formato
        CHECK (cedula ~ '^[0-9]-[0-9]{4}-[0-9]{4}$'),

    CONSTRAINT chk_nombre_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_correo_institucional
        CHECK (
            correo_institucional IS NULL
            OR correo_institucional = ''
            OR correo_institucional LIKE '%@%'
        )
);

CREATE TABLE bitacora_asambleistas (
    id_bitacora_asambleista INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    cedula_anterior VARCHAR(11),
    cedula_nueva VARCHAR(11),
    nombre_anterior VARCHAR(150),
    nombre_nuevo VARCHAR(150),
    correo_anterior VARCHAR(150),
    correo_nuevo VARCHAR(150),
    razon_cambio VARCHAR(255),
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bitacora_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE CASCADE
);

-- =====================================================
-- 3. SEGURIDAD Y AUDITORÍA - ISSUE #0
-- =====================================================

CREATE TABLE sys_usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    id_asambleista INTEGER NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_usuario_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE SET NULL
);

CREATE TABLE sys_rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_permiso (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE sys_usuario_rol (
    id_usuario INTEGER NOT NULL,
    id_rol INTEGER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id_usuario, id_rol),

    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES sys_rol(id_rol)
        ON DELETE CASCADE
);

CREATE TABLE sys_rol_permiso (
    id_rol INTEGER NOT NULL,
    id_permiso INTEGER NOT NULL,

    PRIMARY KEY (id_rol, id_permiso),

    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (id_rol)
        REFERENCES sys_rol(id_rol)
        ON DELETE CASCADE,

    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (id_permiso)
        REFERENCES sys_permiso(id_permiso)
        ON DELETE CASCADE
);

CREATE TABLE sys_log_auditoria (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NULL,
    accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(100),
    detalle TEXT,
    ip_origen VARCHAR(45),
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_log_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL
);

-- =====================================================
-- 4. NORMATIVA - ISSUE #10
-- =====================================================

CREATE TABLE reglamento (
    id_reglamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_normativa VARCHAR(200) NOT NULL,
    sigla VARCHAR(20) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_nombre_normativa_no_vacio CHECK (BTRIM(nombre_normativa) <> ''),
    CONSTRAINT chk_sigla_no_vacia CHECK (BTRIM(sigla) <> '')
);

CREATE TABLE elemento_normativo (
    id_elemento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reglamento INTEGER NOT NULL,
    id_elemento_padre INTEGER NULL,
    id_nivel_reglamento INTEGER NOT NULL,
    numero_etiqueta VARCHAR(20) NOT NULL,
    contenido_texto TEXT NOT NULL,
    orden INTEGER NOT NULL,
    fecha_inicio_vigencia DATE NOT NULL,
    fecha_fin_vigencia DATE NULL,
    id_estado_vigencia INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER NOT NULL,

    CONSTRAINT fk_elemento_reglamento
        FOREIGN KEY (id_reglamento)
        REFERENCES reglamento(id_reglamento)
        ON DELETE RESTRICT,

    CONSTRAINT fk_elemento_padre
        FOREIGN KEY (id_elemento_padre)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE RESTRICT,

    CONSTRAINT fk_elemento_nivel
        FOREIGN KEY (id_nivel_reglamento)
        REFERENCES catalogo_nivel_reglamento(id_nivel_reglamento),

    CONSTRAINT fk_elemento_estado_vigencia
        FOREIGN KEY (id_estado_vigencia)
        REFERENCES catalogo_estado_vigencia(id_estado_vigencia),

    CONSTRAINT fk_elemento_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario),

    CONSTRAINT chk_fechas_vigencia
        CHECK (fecha_fin_vigencia IS NULL OR fecha_inicio_vigencia <= fecha_fin_vigencia),

    CONSTRAINT chk_orden_positivo
        CHECK (orden > 0),

    CONSTRAINT chk_numero_etiqueta_no_vacio
        CHECK (BTRIM(numero_etiqueta) <> ''),

    CONSTRAINT chk_contenido_texto_no_vacio
        CHECK (BTRIM(contenido_texto) <> '')
);

CREATE INDEX idx_elemento_reglamento ON elemento_normativo(id_reglamento);
CREATE INDEX idx_elemento_padre ON elemento_normativo(id_elemento_padre);
CREATE INDEX idx_elemento_vigencia ON elemento_normativo(fecha_inicio_vigencia, fecha_fin_vigencia);
CREATE INDEX idx_elemento_estado ON elemento_normativo(id_estado_vigencia);

-- Evita que existan dos versiones vigentes del mismo elemento lógico.
CREATE UNIQUE INDEX uq_elemento_vigente
ON elemento_normativo (
    id_reglamento,
    COALESCE(id_elemento_padre, 0),
    numero_etiqueta
)
WHERE id_estado_vigencia = 1 AND fecha_fin_vigencia IS NULL;

-- =====================================================
-- 5. NOMBRAMIENTOS - ISSUE #14
-- =====================================================

CREATE TABLE nombramiento (
    id_nombramiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    id_sector INTEGER NOT NULL,
    id_puesto INTEGER NOT NULL,
    resolucion_id INTEGER NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    estado VARCHAR(20) DEFAULT 'Activo',
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,

    CONSTRAINT fk_nombramiento_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE CASCADE,

    CONSTRAINT fk_nombramiento_sector
        FOREIGN KEY (id_sector)
        REFERENCES catalogo_sector(id_sector),

    CONSTRAINT fk_nombramiento_puesto
        FOREIGN KEY (id_puesto)
        REFERENCES catalogo_puestos(id_puesto),

    CONSTRAINT fk_nombramiento_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario),

    CONSTRAINT chk_fechas_nombramiento
        CHECK (fecha_fin IS NULL OR fecha_inicio <= fecha_fin),

    CONSTRAINT chk_estado_nombramiento
        CHECK (estado IN ('Activo', 'Finalizado', 'Suspendido'))
);

CREATE INDEX idx_nombramiento_asambleista ON nombramiento(id_asambleista);
CREATE INDEX idx_nombramiento_sector ON nombramiento(id_sector);
CREATE INDEX idx_nombramiento_fechas ON nombramiento(fecha_inicio, fecha_fin);
CREATE INDEX idx_nombramiento_estado ON nombramiento(estado);

CREATE VIEW v_historial_nombramientos AS
SELECT
    n.id_nombramiento,
    a.nombre AS asambleista,
    a.cedula,
    s.nombre AS sector,
    p.nombre_puesto AS puesto,
    n.fecha_inicio,
    n.fecha_fin,
    n.estado,
    CASE
        WHEN n.fecha_fin IS NULL AND n.estado = 'Activo' THEN 'Vigente'
        WHEN n.fecha_fin < CURRENT_DATE THEN 'Vencido'
        ELSE n.estado
    END AS estado_real,
    n.observaciones,
    u.username AS registrado_por,
    n.fecha_registro
FROM nombramiento n
INNER JOIN asambleista a ON n.id_asambleista = a.id_asambleista
INNER JOIN catalogo_sector s ON n.id_sector = s.id_sector
INNER JOIN catalogo_puestos p ON n.id_puesto = p.id_puesto
INNER JOIN sys_usuario u ON n.id_usuario_registro = u.id_usuario;

-- =====================================================
-- 6. REFORMAS Y VERSIONAMIENTO - ISSUE #15
-- =====================================================

CREATE TABLE reforma_aplicada (
    id_reforma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_resolucion INTEGER NULL,
    id_elemento_normativo INTEGER NOT NULL,
    texto_anterior TEXT NOT NULL,
    texto_nuevo TEXT NOT NULL,
    fecha_inicio_vigencia DATE NOT NULL,
    id_tipo_reforma INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER NOT NULL,

    CONSTRAINT fk_reforma_elemento
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reforma_tipo
        FOREIGN KEY (id_tipo_reforma)
        REFERENCES catalogo_tipo_reforma(id_tipo_reforma)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reforma_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE RESTRICT
);

CREATE INDEX idx_reforma_elemento ON reforma_aplicada(id_elemento_normativo);
CREATE INDEX idx_reforma_fecha ON reforma_aplicada(fecha_inicio_vigencia);
CREATE INDEX idx_reforma_tipo ON reforma_aplicada(id_tipo_reforma);

-- =====================================================
-- 7. GESTIÓN DE COMISIONES DE ANÁLISIS - ISSUE #7
-- =====================================================

-- Propuestas
CREATE TABLE IF NOT EXISTS propuesta (
    id_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_propuesta VARCHAR(12) UNIQUE NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    id_tipo_propuesta INTEGER NOT NULL,
    id_estado_propuesta INTEGER NOT NULL,
    id_elemento_normativo INTEGER,
    fecha_presentacion DATE NOT NULL DEFAULT CURRENT_DATE,
    id_usuario_registro INTEGER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_propuesta_tipo
        FOREIGN KEY (id_tipo_propuesta)
        REFERENCES catalogo_tipo_propuesta(id_tipo_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_propuesta_estado
        FOREIGN KEY (id_estado_propuesta)
        REFERENCES catalogo_estado_propuesta(id_estado_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_propuesta_elemento
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE SET NULL,

    CONSTRAINT fk_propuesta_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    -- Formato: AIR-XXX-YYYY
    CONSTRAINT chk_numero_propuesta_formato
        CHECK (numero_propuesta ~ '^AIR-[0-9]{3}-[0-9]{4}$'),

    CONSTRAINT chk_titulo_propuesta_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

CREATE TABLE IF NOT EXISTS proponente_propuesta (
    id_proponente_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propuesta INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    rol_proponente VARCHAR(50) DEFAULT 'Proponente',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_proponente_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE CASCADE,

    CONSTRAINT fk_proponente_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT uq_proponente_propuesta
        UNIQUE (id_propuesta, id_asambleista)
);

-- Comisiones
CREATE TABLE IF NOT EXISTS comision (
    id_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_comision INTEGER NOT NULL,
    nombre_comision VARCHAR(150) NOT NULL,
    objeto TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_comision_tipo
        FOREIGN KEY (id_tipo_comision)
        REFERENCES catalogo_tipo_comision(id_tipo_comision)
        ON DELETE RESTRICT,

    CONSTRAINT chk_nombre_comision_no_vacio
        CHECK (BTRIM(nombre_comision) <> '')
);

CREATE TABLE IF NOT EXISTS proposito_comision (
    id_proposito_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    id_propuesta INTEGER NOT NULL,
    texto TEXT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_proposito_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_proposito_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT chk_texto_proposito_no_vacio
        CHECK (BTRIM(texto) <> '')
);

-- Integrantes de Comisión
CREATE TABLE IF NOT EXISTS integrante_comision (
    id_integrante_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    id_rol_comision INTEGER NOT NULL,
    fecha_ingreso_nombramiento DATE NOT NULL,
    fecha_fin_nombramiento DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_integrante_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_integrante_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_integrante_rol
        FOREIGN KEY (id_rol_comision)
        REFERENCES catalogo_rol_comision(id_rol_comision)
        ON DELETE RESTRICT,

    CONSTRAINT chk_estado_integrante
        CHECK (estado IN ('Activo', 'Inactivo')),

    CONSTRAINT chk_fechas_integrante
        CHECK (
            fecha_fin_nombramiento IS NULL
            OR fecha_fin_nombramiento >= fecha_ingreso_nombramiento
        )
);

CREATE TABLE IF NOT EXISTS bitacora_integrante_comision (
    id_bitacora_integrante_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_integrante_comision INTEGER NOT NULL,
    id_comision INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    id_rol_comision INTEGER NOT NULL,
    fecha_ingreso_nombramiento DATE NOT NULL,
    fecha_fin_nombramiento DATE,
    estado VARCHAR(20) NOT NULL,
    accion VARCHAR(20) NOT NULL,
    fecha_bitacora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bitacora_integrante
        FOREIGN KEY (id_integrante_comision)
        REFERENCES integrante_comision(id_integrante_comision)
        ON DELETE CASCADE
);

-- Sesiones de Comisión y Agenda
CREATE TABLE IF NOT EXISTS sesion_comision (
    id_sesion_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    observaciones TEXT,

    CONSTRAINT fk_sesion_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS punto_agenda_sesion_comision (
    id_punto_agenda_sesion_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion_comision INTEGER NOT NULL,
    id_proposito_comision INTEGER NOT NULL,
    id_tipo_tramite INTEGER NOT NULL,
    orden INTEGER NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,

    CONSTRAINT fk_punto_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_punto_proposito
        FOREIGN KEY (id_proposito_comision)
        REFERENCES proposito_comision(id_proposito_comision)
        ON DELETE RESTRICT,

    CONSTRAINT fk_punto_tipo_tramite
        FOREIGN KEY (id_tipo_tramite)
        REFERENCES catalogo_tipo_tramite(id_tipo_tramite)
        ON DELETE RESTRICT,

    CONSTRAINT uq_orden_sesion_comision
        UNIQUE (id_sesion_comision, orden),

    CONSTRAINT chk_orden_punto_comision
        CHECK (orden > 0),

    CONSTRAINT chk_titulo_punto_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

-- Informes del Directorio y Justificación Legal
CREATE TABLE IF NOT EXISTS informe_directorio (
    id_informe INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    id_propuesta INTEGER NOT NULL,
    id_sesion_comision INTEGER,
    titulo VARCHAR(200) NOT NULL,
    recomendacion TEXT,
    fecha_presentacion DATE,

    CONSTRAINT fk_informe_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE RESTRICT,

    CONSTRAINT fk_informe_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_informe_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE SET NULL,

    CONSTRAINT chk_titulo_informe_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

CREATE TABLE IF NOT EXISTS justificacion_legal (
    id_argumento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    es_considerando BOOLEAN NOT NULL,
    contenido TEXT NOT NULL,

    CONSTRAINT chk_contenido_argumento_no_vacio
        CHECK (BTRIM(contenido) <> '')
);

CREATE TABLE IF NOT EXISTS justificaciones_por_informe (
    id_informe INTEGER NOT NULL,
    id_argumento INTEGER NOT NULL,
    orden_aparicion INTEGER NOT NULL,

    PRIMARY KEY (id_informe, id_argumento),

    CONSTRAINT fk_justificacion_informe
        FOREIGN KEY (id_informe)
        REFERENCES informe_directorio(id_informe)
        ON DELETE CASCADE,

    CONSTRAINT fk_justificacion_argumento
        FOREIGN KEY (id_argumento)
        REFERENCES justificacion_legal(id_argumento)
        ON DELETE RESTRICT,

    CONSTRAINT chk_orden_justificacion
        CHECK (orden_aparicion > 0),

    CONSTRAINT uq_orden_justificacion_informe
        UNIQUE (id_informe, orden_aparicion)
);

-- Asistencia a Sesiones de Comisión
CREATE TABLE IF NOT EXISTS asistencia_sesion_comision (
    id_asistencia_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    id_sesion_comision INTEGER NOT NULL,
    id_comision INTEGER NOT NULL,
    id_estado_asistencia INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asistencia_comision_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asistencia_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_estado
        FOREIGN KEY (id_estado_asistencia)
        REFERENCES catalogo_estado_asistencia(id_estado_asistencia)
        ON DELETE RESTRICT,

    CONSTRAINT uq_asistencia_comision
        UNIQUE (id_asambleista, id_sesion_comision)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_propuesta_numero ON propuesta(numero_propuesta);
CREATE INDEX IF NOT EXISTS idx_propuesta_estado ON propuesta(id_estado_propuesta);
CREATE INDEX IF NOT EXISTS idx_propuesta_tipo ON propuesta(id_tipo_propuesta);
CREATE INDEX IF NOT EXISTS idx_proponente_propuesta ON proponente_propuesta(id_propuesta);
CREATE INDEX IF NOT EXISTS idx_proponente_asambleista ON proponente_propuesta(id_asambleista);

CREATE INDEX IF NOT EXISTS idx_proposito_comision ON proposito_comision(id_comision);
CREATE INDEX IF NOT EXISTS idx_proposito_propuesta ON proposito_comision(id_propuesta);

CREATE INDEX IF NOT EXISTS idx_integrante_comision ON integrante_comision(id_comision);
CREATE INDEX IF NOT EXISTS idx_integrante_asambleista ON integrante_comision(id_asambleista);
CREATE INDEX IF NOT EXISTS idx_integrante_fechas ON integrante_comision(fecha_ingreso_nombramiento, fecha_fin_nombramiento);

CREATE INDEX IF NOT EXISTS idx_sesion_comision ON sesion_comision(id_comision);
CREATE INDEX IF NOT EXISTS idx_sesion_comision_fecha ON sesion_comision(fecha_hora);

CREATE INDEX IF NOT EXISTS idx_informe_comision ON informe_directorio(id_comision);
CREATE INDEX IF NOT EXISTS idx_informe_propuesta ON informe_directorio(id_propuesta);

CREATE INDEX IF NOT EXISTS idx_asistencia_comision_sesion ON asistencia_sesion_comision(id_sesion_comision);
CREATE INDEX IF NOT EXISTS idx_asistencia_comision_asambleista ON asistencia_sesion_comision(id_asambleista);

-- ==========================================================
-- 8. REGISTRO DE SESIONES Y MEMORIA DE VOTACIÓN - ISSUE #5
-- ==========================================================

-- Sesiones
CREATE TABLE IF NOT EXISTS sesion (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_modalidad INTEGER NOT NULL,
    id_tipo_sesion INTEGER NOT NULL,
    numero_sesion VARCHAR(50) UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME,
    hora_fin TIME,
    link_acta VARCHAR(500),
    quorum_requerido INTEGER,
    total_asambleistas INTEGER,
    estado VARCHAR(30) DEFAULT 'Programada',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER,

    CONSTRAINT fk_sesion_modalidad
        FOREIGN KEY (id_tipo_modalidad)
        REFERENCES catalogo_tipo_modalidad(id_tipo_modalidad)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesion_tipo
        FOREIGN KEY (id_tipo_sesion)
        REFERENCES catalogo_tipo_sesion(id_tipo_sesion)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesion_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_sesion
        CHECK (estado IN ('Programada', 'En Curso', 'Finalizada', 'Cancelada')),

    CONSTRAINT chk_numero_sesion_no_vacio
        CHECK (BTRIM(numero_sesion) <> ''),

    CONSTRAINT chk_horas_sesion
        CHECK (hora_fin IS NULL OR hora_inicio IS NULL OR hora_fin >= hora_inicio),

    CONSTRAINT chk_totales_sesion
        CHECK (total_asambleistas IS NULL OR total_asambleistas >= 0),

    CONSTRAINT chk_quorum_requerido_sesion
        CHECK (quorum_requerido IS NULL OR quorum_requerido >= 0)
);

-- Actas
CREATE TABLE IF NOT EXISTS acta (
    id_acta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    numero_acta VARCHAR(50) UNIQUE NOT NULL,
    fecha_aprobacion DATE,
    url_documento VARCHAR(500),
    contenido_resumen TEXT,
    observaciones TEXT,
    estado VARCHAR(30) DEFAULT 'Borrador',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER,

    CONSTRAINT fk_acta_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_acta_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_acta
        CHECK (estado IN ('Borrador', 'En Revision', 'Aprobada', 'Publicada')),

    CONSTRAINT chk_numero_acta_no_vacio
        CHECK (BTRIM(numero_acta) <> '')
);

CREATE TABLE IF NOT EXISTS punto_agenda_sesion (
    id_punto_agenda_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    id_propuesta INTEGER,
    orden INTEGER NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,

    CONSTRAINT fk_punto_agenda_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_punto_agenda_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT uq_orden_agenda_sesion
        UNIQUE (id_sesion, orden),

    CONSTRAINT chk_orden_agenda_sesion
        CHECK (orden > 0),

    CONSTRAINT chk_titulo_agenda_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

-- Votación
CREATE TABLE IF NOT EXISTS votacion (
    id_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    id_propuesta INTEGER,
    id_elemento_normativo INTEGER,
    numero_votacion VARCHAR(50),
    tipo_votacion VARCHAR(30) DEFAULT 'Publica',
    votos_favor INTEGER DEFAULT 0,
    votos_contra INTEGER DEFAULT 0,
    votos_abstencion INTEGER DEFAULT 0,
    total_votantes INTEGER DEFAULT 0,
    resultado VARCHAR(30) DEFAULT 'Pendiente',
    estado_acuerdo VARCHAR(30) DEFAULT 'Borrador',
    fecha_firma_acuerdo TIMESTAMP,
    id_usuario_firma INTEGER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_votacion_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_votacion_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT fk_votacion_elemento_normativo
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE SET NULL,

    CONSTRAINT fk_votacion_usuario_firma
        FOREIGN KEY (id_usuario_firma)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_tipo_votacion
        CHECK (tipo_votacion IN ('Publica', 'Secreta')),

    CONSTRAINT chk_resultado_votacion
        CHECK (resultado IN ('Aprobada', 'Rechazada', 'Empate', 'Pendiente')),

    CONSTRAINT chk_estado_acuerdo
        CHECK (estado_acuerdo IN ('Borrador', 'Firmado', 'Anulado')),

    CONSTRAINT chk_votos_no_negativos
        CHECK (
            votos_favor >= 0
            AND votos_contra >= 0
            AND votos_abstencion >= 0
            AND total_votantes >= 0
        )
);

CREATE TABLE IF NOT EXISTS bitacora_estado_votacion (
    id_bitacora_estado_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_votacion INTEGER NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo VARCHAR(30) NOT NULL,
    id_usuario INTEGER,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,

    CONSTRAINT fk_bitacora_votacion
        FOREIGN KEY (id_votacion)
        REFERENCES votacion(id_votacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_bitacora_votacion_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_sesion_fecha ON sesion(fecha);
CREATE INDEX IF NOT EXISTS idx_sesion_estado ON sesion(estado);
CREATE INDEX IF NOT EXISTS idx_acta_sesion ON acta(id_sesion);
CREATE INDEX IF NOT EXISTS idx_votacion_sesion ON votacion(id_sesion);
CREATE INDEX IF NOT EXISTS idx_punto_agenda_sesion ON punto_agenda_sesion(id_sesion);
CREATE INDEX IF NOT EXISTS idx_punto_agenda_propuesta ON punto_agenda_sesion(id_propuesta);
CREATE INDEX IF NOT EXISTS idx_votacion_propuesta ON votacion(id_propuesta);
CREATE INDEX IF NOT EXISTS idx_votacion_estado_acuerdo ON votacion(estado_acuerdo);

-- =====================================================
-- 9. CONTROL DE QUÓRUM Y SESIONES - ISSUE #11
-- =====================================================

-- Asistencia de Sesiones Plenarias
CREATE TABLE IF NOT EXISTS asistencia_sesion_plenaria (
    id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    id_sesion INTEGER NOT NULL,
    id_estado_asistencia INTEGER NOT NULL,
    hora_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,

    CONSTRAINT fk_asistencia_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_estado
        FOREIGN KEY (id_estado_asistencia)
        REFERENCES catalogo_estado_asistencia(id_estado_asistencia)
        ON DELETE RESTRICT,

    CONSTRAINT uq_asistencia_sesion
        UNIQUE (id_asambleista, id_sesion)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_asistencia_sesion ON asistencia_sesion_plenaria(id_sesion);
CREATE INDEX IF NOT EXISTS idx_asistencia_asambleista ON asistencia_sesion_plenaria(id_asambleista);

-- =====================================================
-- #. FUNCIONES Y TRIGGERS PARA REGLAS DE NEGOCIO
-- =====================================================

CREATE OR REPLACE FUNCTION fn_bitacora_asambleista()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.cedula <> NEW.cedula
       OR OLD.nombre <> NEW.nombre
       OR COALESCE(OLD.correo_institucional, '') <> COALESCE(NEW.correo_institucional, '') THEN

        INSERT INTO bitacora_asambleistas (
            id_asambleista,
            cedula_anterior,
            cedula_nueva,
            nombre_anterior,
            nombre_nuevo,
            correo_anterior,
            correo_nuevo,
            razon_cambio
        )
        VALUES (
            OLD.id_asambleista,
            OLD.cedula,
            NEW.cedula,
            OLD.nombre,
            NEW.nombre,
            OLD.correo_institucional,
            NEW.correo_institucional,
            'Actualización automática de datos personales'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_auditoria_general()
RETURNS TRIGGER AS $$
DECLARE
    v_id_usuario INTEGER;
    v_registro_id TEXT;
BEGIN
    BEGIN
        v_id_usuario := NULLIF(current_setting('app.current_user_id', TRUE), '')::INTEGER;
    EXCEPTION WHEN OTHERS THEN
        v_id_usuario := NULL;
    END;

    IF TG_TABLE_NAME = 'asambleista' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_asambleista::TEXT; ELSE v_registro_id := NEW.id_asambleista::TEXT; END IF;
    ELSIF TG_TABLE_NAME = 'elemento_normativo' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_elemento::TEXT; ELSE v_registro_id := NEW.id_elemento::TEXT; END IF;
    ELSIF TG_TABLE_NAME = 'nombramiento' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_nombramiento::TEXT; ELSE v_registro_id := NEW.id_nombramiento::TEXT; END IF;
    ELSIF TG_TABLE_NAME = 'reforma_aplicada' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_reforma::TEXT; ELSE v_registro_id := NEW.id_reforma::TEXT; END IF;
    ELSE
        v_registro_id := 'N/A';
    END IF;

    INSERT INTO sys_log_auditoria(id_usuario, accion, tabla_afectada, detalle)
    VALUES (v_id_usuario, TG_OP, TG_TABLE_NAME, 'Operación ' || TG_OP || '. ID: ' || COALESCE(v_registro_id, 'N/A'));

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_versionar_elemento_normativo()
RETURNS TRIGGER AS $$
BEGIN
    -- Si se inserta una nueva versión vigente, la versión vigente anterior, padre y etiqueta pasa automáticamente a Histórico.
    IF NEW.id_estado_vigencia = 1 AND NEW.fecha_fin_vigencia IS NULL THEN
        UPDATE elemento_normativo
        SET id_estado_vigencia = 2,
            fecha_fin_vigencia = NEW.fecha_inicio_vigencia - INTERVAL '1 day'
        WHERE id_reglamento = NEW.id_reglamento
          AND COALESCE(id_elemento_padre, 0) = COALESCE(NEW.id_elemento_padre, 0)
          AND numero_etiqueta = NEW.numero_etiqueta
          AND id_estado_vigencia = 1
          AND fecha_fin_vigencia IS NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_traslape_nombramiento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'Activo' THEN
        IF EXISTS (
            SELECT 1
            FROM nombramiento n
            WHERE n.id_asambleista = NEW.id_asambleista
              AND n.id_sector = NEW.id_sector
              AND n.estado = 'Activo'
              AND n.id_nombramiento <> COALESCE(NEW.id_nombramiento, -1)
              AND NEW.fecha_inicio <= COALESCE(n.fecha_fin, DATE '9999-12-31')
              AND COALESCE(NEW.fecha_fin, DATE '9999-12-31') >= n.fecha_inicio
        ) THEN
            RAISE EXCEPTION 'El asambleísta ya tiene un nombramiento activo en ese sector durante ese periodo.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_versionar_elemento_normativo
BEFORE INSERT ON elemento_normativo
FOR EACH ROW
EXECUTE FUNCTION fn_versionar_elemento_normativo();

CREATE TRIGGER tg_validar_traslape_nombramiento
BEFORE INSERT OR UPDATE ON nombramiento
FOR EACH ROW
EXECUTE FUNCTION fn_validar_traslape_nombramiento();

CREATE TRIGGER tg_bitacora_asambleista
AFTER UPDATE ON asambleista
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_asambleista();

CREATE TRIGGER tg_auditoria_asambleista
AFTER INSERT OR UPDATE OR DELETE ON asambleista
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

CREATE TRIGGER tg_auditoria_elemento_normativo
AFTER INSERT OR UPDATE OR DELETE ON elemento_normativo
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

CREATE TRIGGER tg_auditoria_nombramiento
AFTER INSERT OR UPDATE OR DELETE ON nombramiento
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

CREATE TRIGGER tg_auditoria_reforma_aplicada
AFTER INSERT OR UPDATE OR DELETE ON reforma_aplicada
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

-- Sprint 3:

CREATE OR REPLACE FUNCTION fn_validar_traslape_integrante_comision()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'Activo' THEN
        IF EXISTS (
            SELECT 1
            FROM integrante_comision ic
            WHERE ic.id_comision = NEW.id_comision
              AND ic.id_asambleista = NEW.id_asambleista
              AND ic.estado = 'Activo'
              AND ic.id_integrante_comision <> COALESCE(NEW.id_integrante_comision, -1)
              AND NEW.fecha_ingreso_nombramiento <= COALESCE(ic.fecha_fin_nombramiento, DATE '9999-12-31')
              AND COALESCE(NEW.fecha_fin_nombramiento, DATE '9999-12-31') >= ic.fecha_ingreso_nombramiento
        ) THEN
            RAISE EXCEPTION 'El asambleísta ya tiene un nombramiento activo en esa comisión durante ese periodo.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_bitacora_integrante_comision()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO bitacora_integrante_comision (
        id_integrante_comision,
        id_comision,
        id_asambleista,
        id_rol_comision,
        fecha_ingreso_nombramiento,
        fecha_fin_nombramiento,
        estado,
        accion
    )
    VALUES (
        COALESCE(NEW.id_integrante_comision, OLD.id_integrante_comision),
        COALESCE(NEW.id_comision, OLD.id_comision),
        COALESCE(NEW.id_asambleista, OLD.id_asambleista),
        COALESCE(NEW.id_rol_comision, OLD.id_rol_comision),
        COALESCE(NEW.fecha_ingreso_nombramiento, OLD.fecha_ingreso_nombramiento),
        COALESCE(NEW.fecha_fin_nombramiento, OLD.fecha_fin_nombramiento),
        COALESCE(NEW.estado, OLD.estado),
        TG_OP
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_punto_agenda_comision()
RETURNS TRIGGER AS $$
DECLARE
    v_comision_sesion INTEGER;
    v_comision_proposito INTEGER;
BEGIN
    SELECT id_comision
    INTO v_comision_sesion
    FROM sesion_comision
    WHERE id_sesion_comision = NEW.id_sesion_comision;

    SELECT id_comision
    INTO v_comision_proposito
    FROM proposito_comision
    WHERE id_proposito_comision = NEW.id_proposito_comision;

    IF v_comision_sesion <> v_comision_proposito THEN
        RAISE EXCEPTION 'El propósito de comisión no pertenece a la misma comisión de la sesión.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_informe_directorio()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM proposito_comision pc
        WHERE pc.id_comision = NEW.id_comision
          AND pc.id_propuesta = NEW.id_propuesta
    ) THEN
        RAISE EXCEPTION 'La propuesta del informe no está asociada a esa comisión.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_asistencia_comision()
RETURNS TRIGGER AS $$
DECLARE
    v_comision_sesion INTEGER;
    v_fecha_sesion DATE;
BEGIN
    SELECT id_comision, fecha_hora::DATE
    INTO v_comision_sesion, v_fecha_sesion
    FROM sesion_comision
    WHERE id_sesion_comision = NEW.id_sesion_comision;

    IF v_comision_sesion <> NEW.id_comision THEN
        RAISE EXCEPTION 'La sesión indicada no pertenece a la comisión indicada.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM integrante_comision ic
        WHERE ic.id_comision = NEW.id_comision
          AND ic.id_asambleista = NEW.id_asambleista
          AND ic.estado = 'Activo'
          AND ic.fecha_ingreso_nombramiento <= v_fecha_sesion
          AND COALESCE(ic.fecha_fin_nombramiento, DATE '9999-12-31') >= v_fecha_sesion
    ) THEN
        RAISE EXCEPTION 'Solo se puede registrar asistencia de integrantes activos de la comisión en la fecha de la sesión.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_traslape_integrante_comision
BEFORE INSERT OR UPDATE ON integrante_comision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_traslape_integrante_comision();

CREATE TRIGGER tg_bitacora_integrante_comision
AFTER INSERT OR UPDATE OR DELETE ON integrante_comision
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_integrante_comision();

CREATE TRIGGER tg_validar_punto_agenda_comision
BEFORE INSERT OR UPDATE ON punto_agenda_sesion_comision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_punto_agenda_comision();

CREATE TRIGGER tg_validar_informe_directorio
BEFORE INSERT OR UPDATE ON informe_directorio
FOR EACH ROW
EXECUTE FUNCTION fn_validar_informe_directorio();

CREATE TRIGGER tg_validar_asistencia_comision
BEFORE INSERT OR UPDATE ON asistencia_sesion_comision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_asistencia_comision();

CREATE OR REPLACE FUNCTION fn_validar_resumen_votacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.total_votantes :=
        COALESCE(NEW.votos_favor, 0)
        + COALESCE(NEW.votos_contra, 0)
        + COALESCE(NEW.votos_abstencion, 0);

    IF NEW.estado_acuerdo = 'Firmado' AND NEW.fecha_firma_acuerdo IS NULL THEN
        NEW.fecha_firma_acuerdo := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_resumen_votacion
BEFORE INSERT OR UPDATE ON votacion
FOR EACH ROW
EXECUTE FUNCTION fn_validar_resumen_votacion();

CREATE OR REPLACE FUNCTION fn_bitacora_estado_votacion()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.estado_acuerdo <> NEW.estado_acuerdo THEN
        INSERT INTO bitacora_estado_votacion (
            id_votacion,
            estado_anterior,
            estado_nuevo,
            id_usuario,
            observaciones
        )
        VALUES (
            NEW.id_votacion,
            OLD.estado_acuerdo,
            NEW.estado_acuerdo,
            NEW.id_usuario_firma,
            'Cambio automático de estado de acuerdo'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_bitacora_estado_votacion
AFTER UPDATE ON votacion
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_estado_votacion();

CREATE OR REPLACE FUNCTION fn_total_asambleistas_activos(p_fecha DATE)
RETURNS INTEGER AS $$
DECLARE
    v_total INTEGER;
BEGIN
    SELECT COUNT(DISTINCT n.id_asambleista)
    INTO v_total
    FROM nombramiento n
    WHERE n.estado = 'Activo'
      AND n.fecha_inicio <= p_fecha
      AND COALESCE(n.fecha_fin, DATE '9999-12-31') >= p_fecha;

    RETURN COALESCE(v_total, 0);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_asistentes_para_quorum(p_id_sesion INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_total INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO v_total
    FROM asistencia_sesion_plenaria asp
    INNER JOIN catalogo_estado_asistencia cea
        ON asp.id_estado_asistencia = cea.id_estado_asistencia
    WHERE asp.id_sesion = p_id_sesion
      AND cea.nombre IN ('Presente', 'Retardo');

    RETURN COALESCE(v_total, 0);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_quorum_requerido(p_id_sesion INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_total_asambleistas INTEGER;
    v_porcentaje NUMERIC(5,2);
    v_requerido INTEGER;
BEGIN
    SELECT
        COALESCE(s.total_asambleistas, fn_total_asambleistas_activos(s.fecha)),
        cts.quorum_porcentaje
    INTO v_total_asambleistas, v_porcentaje
    FROM sesion s
    INNER JOIN catalogo_tipo_sesion cts
        ON s.id_tipo_sesion = cts.id_tipo_sesion
    WHERE s.id_sesion = p_id_sesion;

    IF v_total_asambleistas IS NULL OR v_total_asambleistas = 0 THEN
        RAISE EXCEPTION 'No se puede calcular quórum: no hay asambleístas activos para la fecha de la sesión.';
    END IF;

    v_requerido := CEIL(v_total_asambleistas * (v_porcentaje / 100.0));

    RETURN v_requerido;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_quorum(p_id_sesion INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
    v_presentes INTEGER;
    v_requerido INTEGER;
BEGIN
    v_presentes := fn_asistentes_para_quorum(p_id_sesion);
    v_requerido := fn_quorum_requerido(p_id_sesion);

    RETURN v_presentes >= v_requerido;
END;
$$ LANGUAGE plpgsql;

-- Calcular Resultado de Votación
CREATE OR REPLACE FUNCTION fn_calcular_resultado_votacion(
    p_votos_favor INTEGER,
    p_votos_contra INTEGER,
    p_tipo_mayoria VARCHAR
)
RETURNS VARCHAR AS $$
DECLARE
    v_total INTEGER;
    v_umbral NUMERIC;
BEGIN
    v_total := p_votos_favor + p_votos_contra;

    IF v_total = 0 THEN
        RETURN 'Pendiente';
    END IF;

    IF p_tipo_mayoria = 'Calificada' THEN
        v_umbral := v_total * (2.0 / 3.0);
        IF p_votos_favor >= CEIL(v_umbral) THEN
            RETURN 'Aprobada';
        ELSE
            RETURN 'Rechazada';
        END IF;
    ELSE
        IF p_votos_favor > p_votos_contra THEN
            RETURN 'Aprobada';
        ELSIF p_votos_favor = p_votos_contra THEN
            RETURN 'Empate';
        ELSE
            RETURN 'Rechazada';
        END IF;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Actualizar Resumen de Quórum en Sesión
CREATE OR REPLACE FUNCTION fn_actualizar_resumen_quorum()
RETURNS TRIGGER AS $$
DECLARE
    v_id_sesion INTEGER;
    v_total INTEGER;
    v_requerido INTEGER;
BEGIN
    v_id_sesion := COALESCE(NEW.id_sesion, OLD.id_sesion);

    SELECT fn_total_asambleistas_activos(fecha)
    INTO v_total
    FROM sesion
    WHERE id_sesion = v_id_sesion;

    v_requerido := fn_quorum_requerido(v_id_sesion);

    UPDATE sesion
    SET total_asambleistas = v_total,
        quorum_requerido   = v_requerido
    WHERE id_sesion = v_id_sesion;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_actualizar_resumen_quorum
AFTER INSERT OR UPDATE OR DELETE ON asistencia_sesion_plenaria
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_resumen_quorum();

-- Bloquear Votación sin Quórum
CREATE OR REPLACE FUNCTION fn_bloquear_votacion_sin_quorum()
RETURNS TRIGGER AS $$
DECLARE
    v_presentes INTEGER;
    v_requerido INTEGER;
BEGIN
    v_presentes := fn_asistentes_para_quorum(NEW.id_sesion);
    v_requerido := fn_quorum_requerido(NEW.id_sesion);

    IF v_presentes < v_requerido THEN
        RAISE EXCEPTION
            'Quórum insuficiente. Presentes: %, requeridos: %. No se puede registrar la votación.',
            v_presentes,
            v_requerido;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_quorum
BEFORE INSERT OR UPDATE ON votacion
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_votacion_sin_quorum();

-- =====================================================
-- #. VISTAS
-- =====================================================

CREATE OR REPLACE VIEW v_proponentes_propuesta AS
SELECT
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    pp.rol_proponente
FROM proponente_propuesta pp
JOIN propuesta p ON pp.id_propuesta = p.id_propuesta
JOIN asambleista a ON pp.id_asambleista = a.id_asambleista;

CREATE OR REPLACE VIEW v_integrantes_comision AS
SELECT
    ic.id_integrante_comision,
    c.id_comision,
    c.nombre_comision,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    rc.nombre_rol,
    ic.fecha_ingreso_nombramiento,
    ic.fecha_fin_nombramiento,
    ic.estado
FROM integrante_comision ic
JOIN comision c ON ic.id_comision = c.id_comision
JOIN asambleista a ON ic.id_asambleista = a.id_asambleista
JOIN catalogo_rol_comision rc ON ic.id_rol_comision = rc.id_rol_comision;

CREATE OR REPLACE VIEW v_asistencia_comision AS
SELECT
    asc2.id_asistencia_comision,
    c.id_comision,
    c.nombre_comision,
    sc.id_sesion_comision,
    sc.fecha_hora,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    ea.nombre AS estado_asistencia
FROM asistencia_sesion_comision asc2
JOIN sesion_comision sc ON asc2.id_sesion_comision = sc.id_sesion_comision
JOIN comision c ON asc2.id_comision = c.id_comision
JOIN asambleista a ON asc2.id_asambleista = a.id_asambleista
JOIN catalogo_estado_asistencia ea ON asc2.id_estado_asistencia = ea.id_estado_asistencia;

CREATE OR REPLACE VIEW v_informes_comision_certificacion AS
SELECT
    i.id_informe,
    c.id_comision,
    c.nombre_comision,
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    i.titulo AS titulo_informe,
    i.recomendacion,
    i.fecha_presentacion
FROM informe_directorio i
JOIN comision c ON i.id_comision = c.id_comision
JOIN propuesta p ON i.id_propuesta = p.id_propuesta;

CREATE OR REPLACE VIEW v_memoria_votacion_sesion AS
SELECT
    v.id_votacion,
    s.id_sesion,
    s.numero_sesion,
    s.fecha,
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    v.numero_votacion,
    v.tipo_votacion,
    v.votos_favor,
    v.votos_contra,
    v.votos_abstencion,
    v.total_votantes,
    v.resultado,
    v.estado_acuerdo,
    v.fecha_firma_acuerdo
FROM votacion v
JOIN sesion s ON v.id_sesion = s.id_sesion
LEFT JOIN propuesta p ON v.id_propuesta = p.id_propuesta;

CREATE OR REPLACE VIEW v_estado_quorum_sesion AS
SELECT
    s.id_sesion,
    s.numero_sesion,
    s.fecha,
    cts.nombre AS tipo_sesion,
    cts.quorum_porcentaje,
    COALESCE(s.total_asambleistas, fn_total_asambleistas_activos(s.fecha)) AS total_asambleistas,
    fn_asistentes_para_quorum(s.id_sesion) AS presentes_para_quorum,
    fn_quorum_requerido(s.id_sesion) AS quorum_requerido,
    CASE
        WHEN fn_validar_quorum(s.id_sesion) THEN 'Quórum válido'
        ELSE 'Quórum insuficiente'
    END AS estado_quorum
FROM sesion s
INNER JOIN catalogo_tipo_sesion cts
    ON s.id_tipo_sesion = cts.id_tipo_sesion;

-- =====================================================
-- #. DATOS INICIALES
-- =====================================================

INSERT INTO catalogo_sector (id_sector, nombre, descripcion) VALUES
(1, 'Docente', 'Representante del sector docente'),
(2, 'Administrativo', 'Personal administrativo'),
(3, 'Estudiantil', 'Representación estudiantil');

INSERT INTO catalogo_puestos (id_puesto, nombre_puesto, descripcion) VALUES
(1, 'Propietario', 'Representante propietario'),
(2, 'Suplente', 'Representante suplente'),
(3, 'Presidente', 'Presidente del directorio');

INSERT INTO catalogo_nivel_reglamento (id_nivel_reglamento, nombre, orden) VALUES
(1, 'Título', 1),
(2, 'Capítulo', 2),
(3, 'Artículo', 3),
(4, 'Inciso', 4),
(5, 'Sub-inciso', 5);

INSERT INTO catalogo_estado_vigencia (id_estado_vigencia, nombre, descripcion) VALUES
(1, 'Vigente', 'Versión activa actualmente'),
(2, 'Histórico', 'Versión anterior'),
(3, 'Derogado', 'Versión eliminada por reforma');

INSERT INTO catalogo_tipo_reforma (id_tipo_reforma, nombre, descripcion) VALUES
(1, 'Modificación', 'Cambio de texto en un elemento normativo'),
(2, 'Derogación', 'Eliminación de una norma vigente'),
(3, 'Adición', 'Agrega nuevo contenido normativo');

INSERT INTO sys_rol (id_rol, nombre_rol, descripcion) VALUES
(1, 'Administrador', 'Control total del sistema'),
(2, 'Secretaria_AIR', 'Gestión de normativa y certificaciones'),
(3, 'Directorio', 'Planificación de sesiones'),
(4, 'Asambleísta', 'Consulta y creación de mociones'),
(5, 'Consulta', 'Solo lectura');

INSERT INTO sys_permiso (id_permiso, nombre_permiso, descripcion) VALUES
(1, 'crear_mocion', 'Permite crear mociones'),
(2, 'certificar', 'Permite emitir certificaciones'),
(3, 'planificar', 'Permite organizar agenda'),
(4, 'editar_normativa', 'Permite crear y editar normativa'),
(5, 'consultar_normativa', 'Permite consultar normativa');

INSERT INTO sys_usuario (id_usuario, username, password_hash, email, activo) VALUES
(1, 'admin',            '$2b$10$rWP2zXw8iKjddU.PiKBsIul9ELjT0fngspOOOr.J9nu3aO.GOVOfi', 'admin@air.go.cr', TRUE),
(2, 'secretaria',       '$2b$10$UX9sFXgY85ICf5f095TSQOV5VvASwRlD47jO2fBDh4SLYmYYI/IBm', 'secretaria@air.go.cr', TRUE),
(3, 'asambleista_user', '$2b$10$Xn2N1wI6cpSddDVpW/9EAOVayzra8renAPoWJMarkSfTzihUM84km', 'asambleista@air.go.cr', TRUE),
(4, 'directorio01',     '$2b$10$cFyI1ebYFJEzypQOdKj4Te4Dj7QogZ3BjxdIEH8vH/6.fz.IGMYRm', 'directorio@air.go.cr', TRUE),
(5, 'consulta01',       '$2b$10$Vco/qYEuymdbOLrd6BFraO.qYtCyl4hp8QqBwzzT8Jx64KC2sx.3m', 'consulta@air.go.cr', TRUE);

INSERT INTO sys_usuario_rol (id_usuario, id_rol) VALUES
(1, 1),
(2, 2),
(3, 4),
(4, 3),
(5, 5);

INSERT INTO sys_rol_permiso (id_rol, id_permiso) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5),
(2, 2), (2, 4), (2, 5),
(3, 3), (3, 5),
(4, 1), (4, 5),
(5, 5);

INSERT INTO asambleista (id_asambleista, cedula, nombre, correo_institucional) VALUES
(1, '1-2345-6789', 'Ana Rodríguez Mora', 'arodriguez@tec.ac.cr'),
(2, '2-3456-7890', 'Carlos Jiménez Solano', 'cjimenez@tec.ac.cr');

UPDATE asambleista
SET nombre = 'Ana María Rodríguez Mora'
WHERE cedula = '1-2345-6789';

INSERT INTO reglamento (id_reglamento, nombre_normativa, sigla, descripcion) VALUES
(1, 'Estatuto Orgánico del TEC', 'EO', 'Normativa principal institucional'),
(2, 'Reglamento de Enseñanza-Aprendizaje', 'REA', 'Reglamento académico');

INSERT INTO elemento_normativo
(id_elemento, id_reglamento, id_elemento_padre, id_nivel_reglamento, numero_etiqueta, contenido_texto, orden, fecha_inicio_vigencia, id_estado_vigencia, id_usuario_registro)
VALUES
(1, 1, NULL, 1, 'I', 'Disposiciones Preliminares', 1, '2024-01-01', 1, 1),
(2, 1, 1, 2, '1', 'De la Naturaleza Jurídica', 1, '2024-01-01', 1, 1),
(3, 1, 2, 3, '1.1', 'Texto original del artículo 1.', 1, '2024-01-01', 1, 1);

INSERT INTO nombramiento
(id_nombramiento, id_asambleista, id_sector, id_puesto, resolucion_id, fecha_inicio, fecha_fin, estado, id_usuario_registro, observaciones)
VALUES
(1, 1, 1, 1, NULL, '2024-01-15', NULL, 'Activo', 1, 'Nombramiento inicial'),
(2, 2, 2, 2, NULL, '2024-02-01', '2024-12-31', 'Finalizado', 1, 'Nombramiento con fecha de fin');

-- Al insertar una nueva versión vigente del artículo 1.1, el trigger convierte automáticamente la versión anterior en Histórica:
INSERT INTO elemento_normativo
(id_elemento, id_reglamento, id_elemento_padre, id_nivel_reglamento, numero_etiqueta, contenido_texto, orden, fecha_inicio_vigencia, id_estado_vigencia, id_usuario_registro)
VALUES
(4, 1, 2, 3, '1.1', 'Texto reformado del artículo 1.', 1, '2025-01-01', 1, 1),
(5, 1, 3, 4, 'a)', 'Este es un inciso de ejemplo dentro del artículo 1.1', 1, '2024-01-01', 1, 1);

INSERT INTO reforma_aplicada
(id_reforma, id_resolucion, id_elemento_normativo, texto_anterior, texto_nuevo, fecha_inicio_vigencia, id_tipo_reforma, id_usuario_registro)
VALUES
(1, NULL, 3, 'Texto original del artículo 1.', 'Texto reformado del artículo 1.', '2025-01-01', 1, 1);

-- Sprint 3:

INSERT INTO catalogo_estado_propuesta
(id_estado_propuesta, nombre, descripcion)
VALUES
(1, 'Recibida', 'Propuesta recibida por la Secretaría de la AIR'),
(2, 'En análisis', 'Propuesta asignada a comisión para análisis técnico'),
(3, 'Dictaminada', 'Propuesta con informe de comisión'),
(4, 'Aprobada', 'Propuesta aprobada'),
(5, 'Rechazada', 'Propuesta rechazada')
ON CONFLICT (id_estado_propuesta) DO NOTHING;

INSERT INTO catalogo_tipo_propuesta
(id_tipo_propuesta, nombre, descripcion, leyenda_legal)
VALUES
(1, 'Etapa de Procedencia - Consejo Institucional', 'Propuesta enviada por el Consejo Institucional', 'La Secretaría de la AIR no dispone de registros de asistencia para esta etapa de procedencia.'),
(2, 'Etapa de Procedencia - 10% Asamblea', 'Propuesta presentada por al menos el 10% de la Asamblea', 'La propuesta fue presentada por el porcentaje requerido de miembros de la Asamblea.'),
(3, 'Propuesta conciliada', 'Propuesta construida por comisión o grupo de análisis', 'La propuesta conciliada registra proponentes e integrantes participantes.')
ON CONFLICT (id_tipo_propuesta) DO NOTHING;

INSERT INTO catalogo_tipo_comision
(id_tipo_comision, nombre, descripcion)
VALUES
(1, 'Comisión de análisis', 'Comisión encargada del estudio técnico de propuestas'),
(2, 'Comisión especial', 'Comisión temporal creada para un asunto específico')
ON CONFLICT (id_tipo_comision) DO NOTHING;

INSERT INTO catalogo_rol_comision
(id_rol_comision, nombre_rol, descripcion)
VALUES
(1, 'Coordinador', 'Coordina el trabajo de la comisión'),
(2, 'Secretario', 'Registra acuerdos y seguimiento'),
(3, 'Integrante', 'Participa en el análisis técnico')
ON CONFLICT (id_rol_comision) DO NOTHING;

INSERT INTO catalogo_tipo_tramite
(id_tipo_tramite, nombre, descripcion)
VALUES
(1, 'Lectura de acta', 'Revisión y aprobación del acta anterior'),
(2, 'Análisis de propuesta', 'Discusión técnica de una propuesta asignada'),
(3, 'Audiencia', 'Recepción de expertos, proponentes o sectores afectados'),
(4, 'Varios', 'Otros asuntos de la comisión')
ON CONFLICT (id_tipo_tramite) DO NOTHING;

INSERT INTO catalogo_estado_asistencia
(id_estado_asistencia, nombre, descripcion)
VALUES
(1, 'Presente', 'Asistió a la sesión'),
(2, 'Ausente', 'No asistió a la sesión'),
(3, 'Justificado', 'Ausencia justificada')
ON CONFLICT (id_estado_asistencia) DO NOTHING;

INSERT INTO catalogo_tipo_sesion
    (id_tipo_sesion, nombre, descripcion, quorum_porcentaje, requiere_mayoria_calificada)
VALUES
    (1, 'Ordinaria',      'Sesión regular programada en el calendario',      50.00, FALSE),
    (2, 'Extraordinaria', 'Sesión convocada fuera del calendario ordinario',  66.00, TRUE),
    (3, 'Solemne',        'Sesión protocolaria o conmemorativa',              33.00, FALSE)
ON CONFLICT (id_tipo_sesion) DO NOTHING;

INSERT INTO catalogo_tipo_modalidad
    (id_tipo_modalidad, nombre, descripcion)
VALUES
    (1, 'Presencial', 'Sesión realizada en el recinto de la AIR'),
    (2, 'Virtual',    'Sesión realizada por videoconferencia'),
    (3, 'Mixta',      'Combinación de presencial y virtual')
ON CONFLICT (id_tipo_modalidad) DO NOTHING;

-- Presente=1, Ausente=2, Justificado=3 ya fueron insertados por Issue #7
INSERT INTO catalogo_estado_asistencia
    (id_estado_asistencia, nombre, descripcion)
VALUES
    (4, 'Retardo', 'Llegó tarde pero participa en la sesión')
ON CONFLICT (id_estado_asistencia) DO NOTHING;

-- Reiniciar las secuencias después de insertar IDs explícitos:
SELECT setval(pg_get_serial_sequence('catalogo_sector', 'id_sector'), COALESCE(MAX(id_sector), 1)) FROM catalogo_sector;
SELECT setval(pg_get_serial_sequence('catalogo_puestos', 'id_puesto'), COALESCE(MAX(id_puesto), 1)) FROM catalogo_puestos;
SELECT setval(pg_get_serial_sequence('catalogo_nivel_reglamento', 'id_nivel_reglamento'), COALESCE(MAX(id_nivel_reglamento), 1)) FROM catalogo_nivel_reglamento;
SELECT setval(pg_get_serial_sequence('catalogo_estado_vigencia', 'id_estado_vigencia'), COALESCE(MAX(id_estado_vigencia), 1)) FROM catalogo_estado_vigencia;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_reforma', 'id_tipo_reforma'), COALESCE(MAX(id_tipo_reforma), 1)) FROM catalogo_tipo_reforma;
SELECT setval(pg_get_serial_sequence('asambleista', 'id_asambleista'), COALESCE(MAX(id_asambleista), 1)) FROM asambleista;
SELECT setval(pg_get_serial_sequence('sys_usuario', 'id_usuario'), COALESCE(MAX(id_usuario), 1)) FROM sys_usuario;
SELECT setval(pg_get_serial_sequence('sys_rol', 'id_rol'), COALESCE(MAX(id_rol), 1)) FROM sys_rol;
SELECT setval(pg_get_serial_sequence('sys_permiso', 'id_permiso'), COALESCE(MAX(id_permiso), 1)) FROM sys_permiso;
SELECT setval(pg_get_serial_sequence('reglamento', 'id_reglamento'), COALESCE(MAX(id_reglamento), 1)) FROM reglamento;
SELECT setval(pg_get_serial_sequence('elemento_normativo', 'id_elemento'), COALESCE(MAX(id_elemento), 1)) FROM elemento_normativo;
SELECT setval(pg_get_serial_sequence('nombramiento', 'id_nombramiento'), COALESCE(MAX(id_nombramiento), 1)) FROM nombramiento;
SELECT setval(pg_get_serial_sequence('reforma_aplicada', 'id_reforma'), COALESCE(MAX(id_reforma), 1)) FROM reforma_aplicada;

SELECT setval(pg_get_serial_sequence('catalogo_estado_propuesta', 'id_estado_propuesta'), COALESCE(MAX(id_estado_propuesta), 1)) FROM catalogo_estado_propuesta;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_propuesta', 'id_tipo_propuesta'), COALESCE(MAX(id_tipo_propuesta), 1)) FROM catalogo_tipo_propuesta;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_comision', 'id_tipo_comision'), COALESCE(MAX(id_tipo_comision), 1)) FROM catalogo_tipo_comision;
SELECT setval(pg_get_serial_sequence('catalogo_rol_comision', 'id_rol_comision'), COALESCE(MAX(id_rol_comision), 1)) FROM catalogo_rol_comision;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_tramite', 'id_tipo_tramite'), COALESCE(MAX(id_tipo_tramite), 1)) FROM catalogo_tipo_tramite;

SELECT setval(pg_get_serial_sequence('catalogo_tipo_sesion', 'id_tipo_sesion'), COALESCE(MAX(id_tipo_sesion), 1)) FROM catalogo_tipo_sesion;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_modalidad', 'id_tipo_modalidad'), COALESCE(MAX(id_tipo_modalidad), 1)) FROM catalogo_tipo_modalidad;
SELECT setval(pg_get_serial_sequence('catalogo_estado_asistencia', 'id_estado_asistencia'), COALESCE(MAX(id_estado_asistencia), 1)) FROM catalogo_estado_asistencia;


-- ===============================
-- #. CONSULTAS DE VERIFICACIÓN
-- ===============================

-- Verificación de catálogos y seguridad.
SELECT * FROM catalogo_sector;
SELECT * FROM catalogo_puestos;
SELECT * FROM sys_usuario;
SELECT * FROM sys_rol;

-- Verificación de asambleístas y bitácora.
SELECT * FROM asambleista;
SELECT * FROM bitacora_asambleistas;

-- Verificación de jerarquía normativa: Título > Capítulo > Artículo.
SELECT
    hijo.id_elemento,
    hijo.numero_etiqueta,
    hijo.contenido_texto,
    padre.numero_etiqueta AS etiqueta_padre,
    padre.contenido_texto AS texto_padre
FROM elemento_normativo hijo
LEFT JOIN elemento_normativo padre
    ON hijo.id_elemento_padre = padre.id_elemento
ORDER BY hijo.id_elemento;

-- Verificación de versión histórica y vigente.
SELECT
    id_elemento,
    numero_etiqueta,
    contenido_texto,
    fecha_inicio_vigencia,
    fecha_fin_vigencia,
    id_estado_vigencia
FROM elemento_normativo
WHERE numero_etiqueta = '1.1'
ORDER BY fecha_inicio_vigencia;

-- Verificación de historial de nombramientos.
SELECT * FROM v_historial_nombramientos;

-- Verificación de roles por usuario.
SELECT
    u.username,
    r.nombre_rol
FROM sys_usuario u
INNER JOIN sys_usuario_rol ur ON u.id_usuario = ur.id_usuario
INNER JOIN sys_rol r ON ur.id_rol = r.id_rol
ORDER BY u.id_usuario;

-- Verificación de auditoría.
SELECT * FROM sys_log_auditoria ORDER BY id_log;




-- =====================================================
-- #. PRUEBAS SOLICITADAS PARA LA PRESENTACIÓN

-- (Se ejecuta después del código anterior)
-- =====================================================

-- 1) Trigger de Vigencia:

-- Ver el estado actual del artículo '1.1' (elemento 3 y 4)
SELECT
    id_elemento,
    numero_etiqueta,
    contenido_texto,
    fecha_inicio_vigencia,
    fecha_fin_vigencia,
    id_estado_vigencia  -- 1 = Vigente, 2 = Histórico
FROM elemento_normativo
WHERE numero_etiqueta = '1.1'
ORDER BY fecha_inicio_vigencia;

-- Insertar una nueva versión vigente del artículo '1.1'
INSERT INTO elemento_normativo
(id_reglamento, id_elemento_padre, id_nivel_reglamento, numero_etiqueta,
 contenido_texto, orden, fecha_inicio_vigencia, id_estado_vigencia, id_usuario_registro)
VALUES
(1, 2, 3, '1.1',
 'Texto de la segunda reforma del artículo 1.1.',
 1, '2026-01-01', 1, 1);

-- Ver cómo quedaron las versiones después del trigger
SELECT
    id_elemento,
    numero_etiqueta,
    contenido_texto,
    fecha_inicio_vigencia,
    fecha_fin_vigencia,
    id_estado_vigencia  -- Elemento 4 ahora debe ser 2 (Histórico)
FROM elemento_normativo
WHERE numero_etiqueta = '1.1'
ORDER BY fecha_inicio_vigencia;


-- 2) SP de Nombramientros:

-- Ver Nombramiento activo de Ana en sector Docente
SELECT
    n.id_nombramiento,
    a.nombre,
    s.nombre AS sector,
    n.fecha_inicio,
    n.fecha_fin,
    n.estado
FROM nombramiento n
JOIN asambleista a ON n.id_asambleista = a.id_asambleista
JOIN catalogo_sector s ON n.id_sector = s.id_sector
WHERE n.id_asambleista = 1 AND n.id_sector = 1;

-- Debe fallar: traslape de nombramiento activo en el mismo sector
INSERT INTO nombramiento (id_asambleista, id_sector, id_puesto, fecha_inicio, fecha_fin, estado, id_usuario_registro)
VALUES (1, 1, 2, '2024-03-01', '2024-06-01', 'Activo', 1);


-- 3) Audit Log:

-- Ver registros actuales
SELECT
    id_log,
    accion,
    tabla_afectada,
    detalle
FROM sys_log_auditoria
ORDER BY id_log DESC
LIMIT 5;

-- Hacer un UPDATE visible (cambiar correo de Ana)
UPDATE asambleista
SET correo_institucional = 'ana.prueba.video@tec.ac.cr'
WHERE id_asambleista = 1;

-- Ver la auditoría nuevamente para visualizar el cambio
SELECT
    id_log,
    id_usuario,
    accion,
    tabla_afectada,
    detalle,
    fecha_hora
FROM sys_log_auditoria
ORDER BY id_log DESC
LIMIT 5;
