-- =====================================================
-- SISTEMA DE GESTIÓN AIR
-- Sprint 2 - Semana 2

-- Motor: Supabase / PostgreSQL
-- Issues integrados: 0, 9, 10, 14, 15
-- =====================================================

-- =====================================================
-- 0. LIMPIEZA PARA EJECUTAR EN ENTORNO LIMPIO
-- =====================================================

DROP VIEW IF EXISTS v_historial_nombramientos CASCADE;

DROP TABLE IF EXISTS reforma_aplicada CASCADE;
DROP TABLE IF EXISTS nombramiento CASCADE;
DROP TABLE IF EXISTS elemento_normativo CASCADE;
DROP TABLE IF EXISTS reglamento CASCADE;
DROP TABLE IF EXISTS sys_log_auditoria CASCADE;
DROP TABLE IF EXISTS sys_rol_permiso CASCADE;
DROP TABLE IF EXISTS sys_usuario_rol CASCADE;
DROP TABLE IF EXISTS sys_permiso CASCADE;
DROP TABLE IF EXISTS sys_rol CASCADE;
DROP TABLE IF EXISTS sys_usuario CASCADE;
DROP TABLE IF EXISTS bitacora_asambleistas CASCADE;
DROP TABLE IF EXISTS asambleista CASCADE;
DROP TABLE IF EXISTS catalogo_tipo_reforma CASCADE;
DROP TABLE IF EXISTS catalogo_estado_vigencia CASCADE;
DROP TABLE IF EXISTS catalogo_nivel_reglamento CASCADE;
DROP TABLE IF EXISTS catalogo_puestos CASCADE;
DROP TABLE IF EXISTS catalogo_sector CASCADE;

DROP FUNCTION IF EXISTS fn_auditoria_general() CASCADE;
DROP FUNCTION IF EXISTS fn_versionar_elemento_normativo() CASCADE;
DROP FUNCTION IF EXISTS fn_validar_traslape_nombramiento() CASCADE;
DROP FUNCTION IF EXISTS fn_bitacora_asambleista() CASCADE;

-- =====================================================
-- 1. CATÁLOGOS COMPARTIDOS
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_sector (
    id_sector INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalogo_puestos (
    id_puesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_puesto VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalogo_nivel_reglamento (
    id_nivel_reglamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    orden INTEGER NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_nivel_orden_positivo CHECK (orden > 0)
);

CREATE TABLE IF NOT EXISTS catalogo_estado_vigencia (
    id_estado_vigencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_reforma (
    id_tipo_reforma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);

-- =====================================================
-- 2. ASAMBLEÍSTAS - ISSUE #9
-- =====================================================

CREATE TABLE asambleista (
    id_asambleista INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(11) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    correo_institucional VARCHAR(150),

    CONSTRAINT chk_cedula_formato
        CHECK (cedula ~ '^[0-9]-[0-9]{4}-[0-9]{4}$'),

    CONSTRAINT chk_nombre_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_correo_institucional
        CHECK (
            correo_institucional IS NULL
            OR correo_institucional = ''
            OR correo_institucional LIKE '%@%'
        )
);

CREATE TABLE bitacora_asambleistas (
    id_bitacora_asambleista INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    cedula_anterior VARCHAR(11),
    cedula_nueva VARCHAR(11),
    nombre_anterior VARCHAR(150),
    nombre_nuevo VARCHAR(150),
    correo_anterior VARCHAR(150),
    correo_nuevo VARCHAR(150),
    razon_cambio VARCHAR(255),
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bitacora_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE CASCADE
);

-- =====================================================
-- 3. SEGURIDAD Y AUDITORÍA - ISSUE #0
-- =====================================================

CREATE TABLE sys_usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    id_asambleista INTEGER NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_usuario_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE SET NULL
);

CREATE TABLE sys_rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_permiso (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE sys_usuario_rol (
    id_usuario INTEGER NOT NULL,
    id_rol INTEGER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id_usuario, id_rol),

    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES sys_rol(id_rol)
        ON DELETE CASCADE
);

CREATE TABLE sys_rol_permiso (
    id_rol INTEGER NOT NULL,
    id_permiso INTEGER NOT NULL,

    PRIMARY KEY (id_rol, id_permiso),

    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (id_rol)
        REFERENCES sys_rol(id_rol)
        ON DELETE CASCADE,

    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (id_permiso)
        REFERENCES sys_permiso(id_permiso)
        ON DELETE CASCADE
);

CREATE TABLE sys_log_auditoria (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NULL,
    accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(100),
    detalle TEXT,
    ip_origen VARCHAR(45),
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_log_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL
);

-- =====================================================
-- 4. NORMATIVA - ISSUE #10
-- =====================================================

CREATE TABLE reglamento (
    id_reglamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_normativa VARCHAR(200) NOT NULL,
    sigla VARCHAR(20) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_nombre_normativa_no_vacio CHECK (BTRIM(nombre_normativa) <> ''),
    CONSTRAINT chk_sigla_no_vacia CHECK (BTRIM(sigla) <> '')
);

CREATE TABLE elemento_normativo (
    id_elemento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reglamento INTEGER NOT NULL,
    id_elemento_padre INTEGER NULL,
    id_nivel_reglamento INTEGER NOT NULL,
    numero_etiqueta VARCHAR(20) NOT NULL,
    contenido_texto TEXT NOT NULL,
    orden INTEGER NOT NULL,
    fecha_inicio_vigencia DATE NOT NULL,
    fecha_fin_vigencia DATE NULL,
    id_estado_vigencia INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER NOT NULL,

    CONSTRAINT fk_elemento_reglamento
        FOREIGN KEY (id_reglamento)
        REFERENCES reglamento(id_reglamento)
        ON DELETE RESTRICT,

    CONSTRAINT fk_elemento_padre
        FOREIGN KEY (id_elemento_padre)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE RESTRICT,

    CONSTRAINT fk_elemento_nivel
        FOREIGN KEY (id_nivel_reglamento)
        REFERENCES catalogo_nivel_reglamento(id_nivel_reglamento),

    CONSTRAINT fk_elemento_estado_vigencia
        FOREIGN KEY (id_estado_vigencia)
        REFERENCES catalogo_estado_vigencia(id_estado_vigencia),

    CONSTRAINT fk_elemento_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario),

    CONSTRAINT chk_fechas_vigencia
        CHECK (fecha_fin_vigencia IS NULL OR fecha_inicio_vigencia <= fecha_fin_vigencia),

    CONSTRAINT chk_orden_positivo
        CHECK (orden > 0),

    CONSTRAINT chk_numero_etiqueta_no_vacio
        CHECK (BTRIM(numero_etiqueta) <> ''),

    CONSTRAINT chk_contenido_texto_no_vacio
        CHECK (BTRIM(contenido_texto) <> '')
);

CREATE INDEX idx_elemento_reglamento ON elemento_normativo(id_reglamento);
CREATE INDEX idx_elemento_padre ON elemento_normativo(id_elemento_padre);
CREATE INDEX idx_elemento_vigencia ON elemento_normativo(fecha_inicio_vigencia, fecha_fin_vigencia);
CREATE INDEX idx_elemento_estado ON elemento_normativo(id_estado_vigencia);

-- Evita que existan dos versiones vigentes del mismo elemento lógico.
CREATE UNIQUE INDEX uq_elemento_vigente
ON elemento_normativo (
    id_reglamento,
    COALESCE(id_elemento_padre, 0),
    numero_etiqueta
)
WHERE id_estado_vigencia = 1 AND fecha_fin_vigencia IS NULL;

-- =====================================================
-- 5. NOMBRAMIENTOS - ISSUE #14
-- =====================================================

CREATE TABLE nombramiento (
    id_nombramiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    id_sector INTEGER NOT NULL,
    id_puesto INTEGER NOT NULL,
    resolucion_id INTEGER NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    estado VARCHAR(20) DEFAULT 'Activo',
    id_usuario_registro INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,

    CONSTRAINT fk_nombramiento_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE CASCADE,

    CONSTRAINT fk_nombramiento_sector
        FOREIGN KEY (id_sector)
        REFERENCES catalogo_sector(id_sector),

    CONSTRAINT fk_nombramiento_puesto
        FOREIGN KEY (id_puesto)
        REFERENCES catalogo_puestos(id_puesto),

    CONSTRAINT fk_nombramiento_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario),

    CONSTRAINT chk_fechas_nombramiento
        CHECK (fecha_fin IS NULL OR fecha_inicio <= fecha_fin),

    CONSTRAINT chk_estado_nombramiento
        CHECK (estado IN ('Activo', 'Finalizado', 'Suspendido'))
);

CREATE INDEX idx_nombramiento_asambleista ON nombramiento(id_asambleista);
CREATE INDEX idx_nombramiento_sector ON nombramiento(id_sector);
CREATE INDEX idx_nombramiento_fechas ON nombramiento(fecha_inicio, fecha_fin);
CREATE INDEX idx_nombramiento_estado ON nombramiento(estado);

CREATE VIEW v_historial_nombramientos AS
SELECT
    n.id_nombramiento,
    a.nombre AS asambleista,
    a.cedula,
    s.nombre AS sector,
    p.nombre_puesto AS puesto,
    n.fecha_inicio,
    n.fecha_fin,
    n.estado,
    CASE
        WHEN n.fecha_fin IS NULL AND n.estado = 'Activo' THEN 'Vigente'
        WHEN n.fecha_fin < CURRENT_DATE THEN 'Vencido'
        ELSE n.estado
    END AS estado_real,
    n.observaciones,
    u.username AS registrado_por,
    n.fecha_registro
FROM nombramiento n
INNER JOIN asambleista a ON n.id_asambleista = a.id_asambleista
INNER JOIN catalogo_sector s ON n.id_sector = s.id_sector
INNER JOIN catalogo_puestos p ON n.id_puesto = p.id_puesto
INNER JOIN sys_usuario u ON n.id_usuario_registro = u.id_usuario;

-- =====================================================
-- 6. REFORMAS Y VERSIONAMIENTO - ISSUE #15
-- =====================================================

CREATE TABLE reforma_aplicada (
    id_reforma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_resolucion INTEGER NULL,
    id_elemento_normativo INTEGER NOT NULL,
    texto_anterior TEXT NOT NULL,
    texto_nuevo TEXT NOT NULL,
    fecha_inicio_vigencia DATE NOT NULL,
    id_tipo_reforma INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER NOT NULL,

    CONSTRAINT fk_reforma_elemento
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reforma_tipo
        FOREIGN KEY (id_tipo_reforma)
        REFERENCES catalogo_tipo_reforma(id_tipo_reforma)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reforma_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE RESTRICT
);

CREATE INDEX idx_reforma_elemento ON reforma_aplicada(id_elemento_normativo);
CREATE INDEX idx_reforma_fecha ON reforma_aplicada(fecha_inicio_vigencia);
CREATE INDEX idx_reforma_tipo ON reforma_aplicada(id_tipo_reforma);

-- =====================================================
-- 7. FUNCIONES Y TRIGGERS PARA REGLAS DE NEGOCIO
-- =====================================================

CREATE OR REPLACE FUNCTION fn_bitacora_asambleista()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.cedula <> NEW.cedula
       OR OLD.nombre <> NEW.nombre
       OR COALESCE(OLD.correo_institucional, '') <> COALESCE(NEW.correo_institucional, '') THEN

        INSERT INTO bitacora_asambleistas (
            id_asambleista,
            cedula_anterior,
            cedula_nueva,
            nombre_anterior,
            nombre_nuevo,
            correo_anterior,
            correo_nuevo,
            razon_cambio
        )
        VALUES (
            OLD.id_asambleista,
            OLD.cedula,
            NEW.cedula,
            OLD.nombre,
            NEW.nombre,
            OLD.correo_institucional,
            NEW.correo_institucional,
            'Actualización automática de datos personales'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_auditoria_general()
RETURNS TRIGGER AS $$
DECLARE
    v_id_usuario INTEGER;
    v_registro_id TEXT;
BEGIN
    BEGIN
        v_id_usuario := NULLIF(current_setting('app.current_user_id', TRUE), '')::INTEGER;
    EXCEPTION WHEN OTHERS THEN
        v_id_usuario := NULL;
    END;

    IF TG_TABLE_NAME = 'asambleista' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_asambleista::TEXT; ELSE v_registro_id := NEW.id_asambleista::TEXT; END IF;
    ELSIF TG_TABLE_NAME = 'elemento_normativo' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_elemento::TEXT; ELSE v_registro_id := NEW.id_elemento::TEXT; END IF;
    ELSIF TG_TABLE_NAME = 'nombramiento' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_nombramiento::TEXT; ELSE v_registro_id := NEW.id_nombramiento::TEXT; END IF;
    ELSIF TG_TABLE_NAME = 'reforma_aplicada' THEN
        IF TG_OP = 'DELETE' THEN v_registro_id := OLD.id_reforma::TEXT; ELSE v_registro_id := NEW.id_reforma::TEXT; END IF;
    ELSE
        v_registro_id := 'N/A';
    END IF;

    INSERT INTO sys_log_auditoria(id_usuario, accion, tabla_afectada, detalle)
    VALUES (v_id_usuario, TG_OP, TG_TABLE_NAME, 'Operación ' || TG_OP || '. ID: ' || COALESCE(v_registro_id, 'N/A'));

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_versionar_elemento_normativo()
RETURNS TRIGGER AS $$
BEGIN
    -- Si se inserta una nueva versión vigente, la versión vigente anterior, padre y etiqueta pasa automáticamente a Histórico.
    IF NEW.id_estado_vigencia = 1 AND NEW.fecha_fin_vigencia IS NULL THEN
        UPDATE elemento_normativo
        SET id_estado_vigencia = 2,
            fecha_fin_vigencia = NEW.fecha_inicio_vigencia - INTERVAL '1 day'
        WHERE id_reglamento = NEW.id_reglamento
          AND COALESCE(id_elemento_padre, 0) = COALESCE(NEW.id_elemento_padre, 0)
          AND numero_etiqueta = NEW.numero_etiqueta
          AND id_estado_vigencia = 1
          AND fecha_fin_vigencia IS NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_traslape_nombramiento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'Activo' THEN
        IF EXISTS (
            SELECT 1
            FROM nombramiento n
            WHERE n.id_asambleista = NEW.id_asambleista
              AND n.id_sector = NEW.id_sector
              AND n.estado = 'Activo'
              AND n.id_nombramiento <> COALESCE(NEW.id_nombramiento, -1)
              AND NEW.fecha_inicio <= COALESCE(n.fecha_fin, DATE '9999-12-31')
              AND COALESCE(NEW.fecha_fin, DATE '9999-12-31') >= n.fecha_inicio
        ) THEN
            RAISE EXCEPTION 'El asambleísta ya tiene un nombramiento activo en ese sector durante ese periodo.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_versionar_elemento_normativo
BEFORE INSERT ON elemento_normativo
FOR EACH ROW
EXECUTE FUNCTION fn_versionar_elemento_normativo();

CREATE TRIGGER tg_validar_traslape_nombramiento
BEFORE INSERT OR UPDATE ON nombramiento
FOR EACH ROW
EXECUTE FUNCTION fn_validar_traslape_nombramiento();

CREATE TRIGGER tg_bitacora_asambleista
AFTER UPDATE ON asambleista
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_asambleista();

CREATE TRIGGER tg_auditoria_asambleista
AFTER INSERT OR UPDATE OR DELETE ON asambleista
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

CREATE TRIGGER tg_auditoria_elemento_normativo
AFTER INSERT OR UPDATE OR DELETE ON elemento_normativo
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

CREATE TRIGGER tg_auditoria_nombramiento
AFTER INSERT OR UPDATE OR DELETE ON nombramiento
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

CREATE TRIGGER tg_auditoria_reforma_aplicada
AFTER INSERT OR UPDATE OR DELETE ON reforma_aplicada
FOR EACH ROW
EXECUTE FUNCTION fn_auditoria_general();

-- =====================================================
-- 8. DATOS INICIALES
-- =====================================================

INSERT INTO catalogo_sector (id_sector, nombre, descripcion) VALUES
(1, 'Docente', 'Representante del sector docente'),
(2, 'Administrativo', 'Personal administrativo'),
(3, 'Estudiantil', 'Representación estudiantil');

INSERT INTO catalogo_puestos (id_puesto, nombre_puesto, descripcion) VALUES
(1, 'Propietario', 'Representante propietario'),
(2, 'Suplente', 'Representante suplente'),
(3, 'Presidente', 'Presidente del directorio');

INSERT INTO catalogo_nivel_reglamento (id_nivel_reglamento, nombre, orden) VALUES
(1, 'Título', 1),
(2, 'Capítulo', 2),
(3, 'Artículo', 3),
(4, 'Inciso', 4),
(5, 'Sub-inciso', 5);

INSERT INTO catalogo_estado_vigencia (id_estado_vigencia, nombre, descripcion) VALUES
(1, 'Vigente', 'Versión activa actualmente'),
(2, 'Histórico', 'Versión anterior'),
(3, 'Derogado', 'Versión eliminada por reforma');

INSERT INTO catalogo_tipo_reforma (id_tipo_reforma, nombre, descripcion) VALUES
(1, 'Modificación', 'Cambio de texto en un elemento normativo'),
(2, 'Derogación', 'Eliminación de una norma vigente'),
(3, 'Adición', 'Agrega nuevo contenido normativo');

INSERT INTO sys_rol (id_rol, nombre_rol, descripcion) VALUES
(1, 'Administrador', 'Control total del sistema'),
(2, 'Secretaria_AIR', 'Gestión de normativa y certificaciones'),
(3, 'Directorio', 'Planificación de sesiones'),
(4, 'Asambleísta', 'Consulta y creación de mociones'),
(5, 'Consulta', 'Solo lectura');

INSERT INTO sys_permiso (id_permiso, nombre_permiso, descripcion) VALUES
(1, 'crear_mocion', 'Permite crear mociones'),
(2, 'certificar', 'Permite emitir certificaciones'),
(3, 'planificar', 'Permite organizar agenda'),
(4, 'editar_normativa', 'Permite crear y editar normativa'),
(5, 'consultar_normativa', 'Permite consultar normativa');

INSERT INTO sys_usuario (id_usuario, username, password_hash, email, activo) VALUES
(1, 'admin', 'Admin123', 'admin@air.go.cr', TRUE),
(2, 'secretaria', 'Secretaria123', 'secretaria@air.go.cr', TRUE),
(3, 'asambleista_user', 'Asamblea123', 'asambleista@air.go.cr', TRUE),
(4, 'directorio01', 'Directorio123', 'directorio@air.go.cr', TRUE),
(5, 'consulta01', 'Consulta123', 'consulta@air.go.cr', TRUE);

INSERT INTO sys_usuario_rol (id_usuario, id_rol) VALUES
(1, 1),
(2, 2),
(3, 4),
(4, 3),
(5, 5);

INSERT INTO sys_rol_permiso (id_rol, id_permiso) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5),
(2, 2), (2, 4), (2, 5),
(3, 3), (3, 5),
(4, 1), (4, 5),
(5, 5);

INSERT INTO asambleista (id_asambleista, cedula, nombre, correo_institucional) VALUES
(1, '1-2345-6789', 'Ana Rodríguez Mora', 'arodriguez@tec.ac.cr'),
(2, '2-3456-7890', 'Carlos Jiménez Solano', 'cjimenez@tec.ac.cr');

UPDATE asambleista
SET nombre = 'Ana María Rodríguez Mora'
WHERE cedula = '1-2345-6789';

INSERT INTO reglamento (id_reglamento, nombre_normativa, sigla, descripcion) VALUES
(1, 'Estatuto Orgánico del TEC', 'EO', 'Normativa principal institucional'),
(2, 'Reglamento de Enseñanza-Aprendizaje', 'REA', 'Reglamento académico');

INSERT INTO elemento_normativo
(id_elemento, id_reglamento, id_elemento_padre, id_nivel_reglamento, numero_etiqueta, contenido_texto, orden, fecha_inicio_vigencia, id_estado_vigencia, id_usuario_registro)
VALUES
(1, 1, NULL, 1, 'I', 'Disposiciones Preliminares', 1, '2024-01-01', 1, 1),
(2, 1, 1, 2, '1', 'De la Naturaleza Jurídica', 1, '2024-01-01', 1, 1),
(3, 1, 2, 3, '1.1', 'Texto original del artículo 1.', 1, '2024-01-01', 1, 1);

INSERT INTO nombramiento
(id_nombramiento, id_asambleista, id_sector, id_puesto, resolucion_id, fecha_inicio, fecha_fin, estado, id_usuario_registro, observaciones)
VALUES
(1, 1, 1, 1, NULL, '2024-01-15', NULL, 'Activo', 1, 'Nombramiento inicial'),
(2, 2, 2, 2, NULL, '2024-02-01', '2024-12-31', 'Finalizado', 1, 'Nombramiento con fecha de fin');

-- Al insertar una nueva versión vigente del artículo 1.1, el trigger convierte automáticamente la versión anterior en Histórica:
INSERT INTO elemento_normativo
(id_elemento, id_reglamento, id_elemento_padre, id_nivel_reglamento, numero_etiqueta, contenido_texto, orden, fecha_inicio_vigencia, id_estado_vigencia, id_usuario_registro)
VALUES
(4, 1, 2, 3, '1.1', 'Texto reformado del artículo 1.', 1, '2025-01-01', 1, 1),
(5, 1, 3, 4, 'a)', 'Este es un inciso de ejemplo dentro del artículo 1.1', 1, '2024-01-01', 1, 1);

INSERT INTO reforma_aplicada
(id_reforma, id_resolucion, id_elemento_normativo, texto_anterior, texto_nuevo, fecha_inicio_vigencia, id_tipo_reforma, id_usuario_registro)
VALUES
(1, NULL, 3, 'Texto original del artículo 1.', 'Texto reformado del artículo 1.', '2025-01-01', 1, 1);

-- Reiniciar las secuencias después de insertar IDs explícitos:
SELECT setval(pg_get_serial_sequence('catalogo_sector', 'id_sector'), COALESCE(MAX(id_sector), 1)) FROM catalogo_sector;
SELECT setval(pg_get_serial_sequence('catalogo_puestos', 'id_puesto'), COALESCE(MAX(id_puesto), 1)) FROM catalogo_puestos;
SELECT setval(pg_get_serial_sequence('catalogo_nivel_reglamento', 'id_nivel_reglamento'), COALESCE(MAX(id_nivel_reglamento), 1)) FROM catalogo_nivel_reglamento;
SELECT setval(pg_get_serial_sequence('catalogo_estado_vigencia', 'id_estado_vigencia'), COALESCE(MAX(id_estado_vigencia), 1)) FROM catalogo_estado_vigencia;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_reforma', 'id_tipo_reforma'), COALESCE(MAX(id_tipo_reforma), 1)) FROM catalogo_tipo_reforma;
SELECT setval(pg_get_serial_sequence('asambleista', 'id_asambleista'), COALESCE(MAX(id_asambleista), 1)) FROM asambleista;
SELECT setval(pg_get_serial_sequence('sys_usuario', 'id_usuario'), COALESCE(MAX(id_usuario), 1)) FROM sys_usuario;
SELECT setval(pg_get_serial_sequence('sys_rol', 'id_rol'), COALESCE(MAX(id_rol), 1)) FROM sys_rol;
SELECT setval(pg_get_serial_sequence('sys_permiso', 'id_permiso'), COALESCE(MAX(id_permiso), 1)) FROM sys_permiso;
SELECT setval(pg_get_serial_sequence('reglamento', 'id_reglamento'), COALESCE(MAX(id_reglamento), 1)) FROM reglamento;
SELECT setval(pg_get_serial_sequence('elemento_normativo', 'id_elemento'), COALESCE(MAX(id_elemento), 1)) FROM elemento_normativo;
SELECT setval(pg_get_serial_sequence('nombramiento', 'id_nombramiento'), COALESCE(MAX(id_nombramiento), 1)) FROM nombramiento;
SELECT setval(pg_get_serial_sequence('reforma_aplicada', 'id_reforma'), COALESCE(MAX(id_reforma), 1)) FROM reforma_aplicada;

-- ===============================
-- 9. CONSULTAS DE VERIFICACIÓN
-- ===============================

-- Verificación de catálogos y seguridad.
SELECT * FROM catalogo_sector;
SELECT * FROM catalogo_puestos;
SELECT * FROM sys_usuario;
SELECT * FROM sys_rol;

-- Verificación de asambleístas y bitácora.
SELECT * FROM asambleista;
SELECT * FROM bitacora_asambleistas;

-- Verificación de jerarquía normativa: Título > Capítulo > Artículo.
SELECT
    hijo.id_elemento,
    hijo.numero_etiqueta,
    hijo.contenido_texto,
    padre.numero_etiqueta AS etiqueta_padre,
    padre.contenido_texto AS texto_padre
FROM elemento_normativo hijo
LEFT JOIN elemento_normativo padre
    ON hijo.id_elemento_padre = padre.id_elemento
ORDER BY hijo.id_elemento;

-- Verificación de versión histórica y vigente.
SELECT
    id_elemento,
    numero_etiqueta,
    contenido_texto,
    fecha_inicio_vigencia,
    fecha_fin_vigencia,
    id_estado_vigencia
FROM elemento_normativo
WHERE numero_etiqueta = '1.1'
ORDER BY fecha_inicio_vigencia;

-- Verificación de historial de nombramientos.
SELECT * FROM v_historial_nombramientos;

-- Verificación de roles por usuario.
SELECT
    u.username,
    r.nombre_rol
FROM sys_usuario u
INNER JOIN sys_usuario_rol ur ON u.id_usuario = ur.id_usuario
INNER JOIN sys_rol r ON ur.id_rol = r.id_rol
ORDER BY u.id_usuario;

-- Verificación de auditoría.
SELECT * FROM sys_log_auditoria ORDER BY id_log;

-- =====================================================
-- 10. PRUEBAS NEGATIVAS OPCIONALES
-- =====================================================
-- Ejecutar una por una (evidencia de rechazo)

-- Debe fallar: cédula repetida.
-- INSERT INTO asambleista (cedula, nombre, correo_institucional)
-- VALUES ('1-2345-6789', 'Persona Duplicada', 'duplicada@tec.ac.cr');

-- Debe fallar: nombre obligatorio vacío.
-- INSERT INTO asambleista (cedula, nombre, correo_institucional)
-- VALUES ('3-4567-8901', '', 'prueba@tec.ac.cr');

-- Debe fallar: traslape de nombramiento activo en el mismo sector.
-- INSERT INTO nombramiento (id_asambleista, id_sector, id_puesto, fecha_inicio, fecha_fin, estado, id_usuario_registro)
-- VALUES (1, 1, 2, '2024-03-01', '2024-06-01', 'Activo', 1);

-- Debe fallar: no se puede borrar un título si tiene capítulos asociados.
-- DELETE FROM elemento_normativo WHERE id_elemento = 1;
