-- =====================================================
-- ISSUE #17: Motor de Certificaciones
-- Sprint 3
-- Motor: Supabase
-- =====================================================

-- =========================
-- TABLAS
-- =========================

CREATE TABLE IF NOT EXISTS control_folio (
    id_control INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio INTEGER NOT NULL,
    ultimo_numero INTEGER DEFAULT 0,
    prefijo VARCHAR(10) DEFAULT 'DAIR',
    formato VARCHAR(30) DEFAULT 'DAIR-{anio}-{numero}',
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_control_folio_anio_prefijo
        UNIQUE (anio, prefijo),

    CONSTRAINT chk_control_folio_anio
        CHECK (anio >= 2000),

    CONSTRAINT chk_control_folio_numero
        CHECK (ultimo_numero >= 0)
);

CREATE TABLE IF NOT EXISTS solicitud_certificacion (
    id_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    fecha_solicitud DATE NOT NULL DEFAULT CURRENT_DATE,
    periodo_desde DATE,
    periodo_hasta DATE,
    estado VARCHAR(20) DEFAULT 'Pendiente',
    observaciones TEXT,
    id_usuario_solicitante INTEGER,
    fecha_respuesta DATE,

    CONSTRAINT fk_solicitud_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_usuario
        FOREIGN KEY (id_usuario_solicitante)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_solicitud_certificacion
        CHECK (estado IN ('Pendiente', 'En Proceso', 'Completada', 'Rechazada')),

    CONSTRAINT chk_periodo_solicitud
        CHECK (periodo_hasta IS NULL OR periodo_desde IS NULL OR periodo_hasta >= periodo_desde)
);

CREATE TABLE IF NOT EXISTS certificacion_emitida (
    id_certificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud INTEGER,
    id_asambleista INTEGER NOT NULL,
    folio_unico VARCHAR(50) UNIQUE NOT NULL,
    hash_seguridad VARCHAR(64) NOT NULL,
    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_emision TIME DEFAULT CURRENT_TIME,
    contenido_json JSONB NOT NULL,
    url_pdf VARCHAR(500),
    estado VARCHAR(20) DEFAULT 'Activa',
    motivo_anulacion TEXT,
    id_usuario_secretaria INTEGER NOT NULL,
    id_certificacion_sustituye INTEGER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_certificacion_solicitud
        FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_certificacion(id_solicitud)
        ON DELETE SET NULL,

    CONSTRAINT fk_certificacion_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_certificacion_usuario
        FOREIGN KEY (id_usuario_secretaria)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT fk_certificacion_sustituye
        FOREIGN KEY (id_certificacion_sustituye)
        REFERENCES certificacion_emitida(id_certificacion)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_certificacion
        CHECK (estado IN ('Activa', 'Anulada', 'Suspendida')),

    CONSTRAINT chk_hash_sha256
        CHECK (hash_seguridad ~ '^[a-f0-9]{64}$')
);

CREATE TABLE IF NOT EXISTS anulacion_certificacion (
    id_anulacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_certificacion INTEGER NOT NULL,
    motivo TEXT NOT NULL,
    fecha_anulacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_anulacion INTEGER NOT NULL,
    justificacion_detalle TEXT,
    id_certificacion_sustituta INTEGER,

    CONSTRAINT fk_anulacion_certificacion
        FOREIGN KEY (id_certificacion)
        REFERENCES certificacion_emitida(id_certificacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_anulacion_usuario
        FOREIGN KEY (id_usuario_anulacion)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT fk_anulacion_sustituta
        FOREIGN KEY (id_certificacion_sustituta)
        REFERENCES certificacion_emitida(id_certificacion)
        ON DELETE SET NULL,

    CONSTRAINT chk_motivo_anulacion_no_vacio
        CHECK (BTRIM(motivo) <> '')
);

CREATE TABLE IF NOT EXISTS certificacion_detalle (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_certificacion INTEGER NOT NULL,
    tipo_elemento VARCHAR(50) NOT NULL,
    id_referencia INTEGER NOT NULL,
    descripcion TEXT,
    orden_aparicion INTEGER DEFAULT 0,
    metadata JSONB,

    CONSTRAINT fk_certificacion_detalle
        FOREIGN KEY (id_certificacion)
        REFERENCES certificacion_emitida(id_certificacion)
        ON DELETE CASCADE,

    CONSTRAINT chk_tipo_elemento_certificacion
        CHECK (tipo_elemento IN ('Sesion', 'Acta', 'Propuesta', 'Comision', 'Votacion', 'Nombramiento', 'Asistencia')),

    CONSTRAINT chk_orden_detalle_certificacion
        CHECK (orden_aparicion >= 0)
);

CREATE TABLE IF NOT EXISTS verificacion_externa (
    id_verificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_certificacion INTEGER NOT NULL,
    codigo_verificacion VARCHAR(80) UNIQUE NOT NULL,
    url_verificacion VARCHAR(500),
    qr_code TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    veces_verificado INTEGER DEFAULT 0,
    ultima_verificacion TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_verificacion_certificacion
        FOREIGN KEY (id_certificacion)
        REFERENCES certificacion_emitida(id_certificacion)
        ON DELETE CASCADE,

    CONSTRAINT chk_verificaciones_no_negativas
        CHECK (veces_verificado >= 0)
);

ALTER TABLE solicitud_certificacion
    ADD COLUMN IF NOT EXISTS id_certificacion_generada INTEGER;

ALTER TABLE solicitud_certificacion
    ADD CONSTRAINT fk_solicitud_certificacion_generada
        FOREIGN KEY (id_certificacion_generada)
        REFERENCES certificacion_emitida(id_certificacion)
        ON DELETE SET NULL;

-- Índices
CREATE INDEX IF NOT EXISTS idx_certificacion_folio ON certificacion_emitida(folio_unico);
CREATE INDEX IF NOT EXISTS idx_certificacion_asambleista ON certificacion_emitida(id_asambleista);
CREATE INDEX IF NOT EXISTS idx_certificacion_fecha ON certificacion_emitida(fecha_emision);
CREATE INDEX IF NOT EXISTS idx_certificacion_estado ON certificacion_emitida(estado);
CREATE INDEX IF NOT EXISTS idx_certificacion_solicitud ON certificacion_emitida(id_solicitud);

CREATE INDEX IF NOT EXISTS idx_detalle_certificacion ON certificacion_detalle(id_certificacion);
CREATE INDEX IF NOT EXISTS idx_detalle_tipo ON certificacion_detalle(tipo_elemento);

CREATE INDEX IF NOT EXISTS idx_verificacion_codigo ON verificacion_externa(codigo_verificacion);
CREATE INDEX IF NOT EXISTS idx_verificacion_certificacion ON verificacion_externa(id_certificacion);

CREATE INDEX IF NOT EXISTS idx_solicitud_asambleista ON solicitud_certificacion(id_asambleista);
CREATE INDEX IF NOT EXISTS idx_solicitud_estado ON solicitud_certificacion(estado);

-- =====================================================
-- FUNCIONES Y TRIGGERS
-- =====================================================

CREATE OR REPLACE FUNCTION fn_generar_folio_certificacion()
RETURNS TEXT AS $$
DECLARE
    v_anio INTEGER;
    v_numero INTEGER;
    v_folio TEXT;
BEGIN
    v_anio := EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;

    INSERT INTO control_folio (anio, ultimo_numero, prefijo)
    VALUES (v_anio, 0, 'DAIR')
    ON CONFLICT (anio, prefijo) DO NOTHING;

    SELECT ultimo_numero + 1
    INTO v_numero
    FROM control_folio
    WHERE anio = v_anio
      AND prefijo = 'DAIR'
    FOR UPDATE;

    UPDATE control_folio
    SET ultimo_numero = v_numero,
        fecha_actualizacion = CURRENT_TIMESTAMP
    WHERE anio = v_anio
      AND prefijo = 'DAIR';

    v_folio := 'DAIR-' || v_anio::TEXT || '-' || LPAD(v_numero::TEXT, 3, '0');

    RETURN v_folio;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_generar_hash_certificacion(p_contenido JSONB)
RETURNS TEXT AS $$
BEGIN
    RETURN ENCODE(DIGEST(p_contenido::TEXT, 'sha256'), 'hex');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_preparar_certificacion()
RETURNS TRIGGER AS $$
DECLARE
    v_codigo TEXT;
BEGIN
    IF NEW.folio_unico IS NULL OR BTRIM(NEW.folio_unico) = '' THEN
        NEW.folio_unico := fn_generar_folio_certificacion();
    END IF;

    IF NEW.contenido_json IS NULL THEN
        RAISE EXCEPTION 'La certificación debe tener contenido_json para calcular el hash.';
    END IF;

    NEW.hash_seguridad := fn_generar_hash_certificacion(NEW.contenido_json);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_crear_verificacion_certificacion()
RETURNS TRIGGER AS $$
DECLARE
    v_codigo TEXT;
BEGIN
    v_codigo := 'VER-' || NEW.folio_unico || '-' || SUBSTRING(NEW.hash_seguridad FROM 1 FOR 10);

    INSERT INTO verificacion_externa (
        id_certificacion,
        codigo_verificacion,
        url_verificacion,
        qr_code
    )
    VALUES (
        NEW.id_certificacion,
        v_codigo,
        '/verificar-certificacion/' || v_codigo,
        v_codigo
    )
    ON CONFLICT (codigo_verificacion) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_anular_certificacion(
    p_id_certificacion INTEGER,
    p_motivo TEXT,
    p_id_usuario_anulacion INTEGER,
    p_id_certificacion_sustituta INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
BEGIN
    IF p_motivo IS NULL OR BTRIM(p_motivo) = '' THEN
        RAISE EXCEPTION 'Debe indicar una justificación obligatoria para anular la certificación.';
    END IF;

    UPDATE certificacion_emitida
    SET estado = 'Anulada',
        motivo_anulacion = p_motivo
    WHERE id_certificacion = p_id_certificacion
      AND estado <> 'Anulada';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'La certificación no existe o ya estaba anulada.';
    END IF;

    INSERT INTO anulacion_certificacion (
        id_certificacion,
        motivo,
        id_usuario_anulacion,
        justificacion_detalle,
        id_certificacion_sustituta
    )
    VALUES (
        p_id_certificacion,
        p_motivo,
        p_id_usuario_anulacion,
        p_motivo,
        p_id_certificacion_sustituta
    );

    UPDATE verificacion_externa
    SET activo = FALSE
    WHERE id_certificacion = p_id_certificacion;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_registrar_verificacion_externa(
    p_codigo_verificacion VARCHAR
)
RETURNS TABLE (
    folio_unico VARCHAR,
    estado VARCHAR,
    hash_seguridad VARCHAR,
    fecha_emision DATE,
    nombre_asambleista VARCHAR,
    mensaje_validacion TEXT
) AS $$
BEGIN
    UPDATE verificacion_externa
    SET veces_verificado = veces_verificado + 1,
        ultima_verificacion = CURRENT_TIMESTAMP
    WHERE codigo_verificacion = p_codigo_verificacion;

    RETURN QUERY
    SELECT
        ce.folio_unico,
        ce.estado,
        ce.hash_seguridad,
        ce.fecha_emision,
        a.nombre,
        CASE
            WHEN ce.estado = 'Activa' AND ve.activo = TRUE
                THEN 'Documento auténtico y vigente'
            WHEN ce.estado = 'Anulada'
                THEN 'Documento inválido: certificación anulada'
            ELSE 'Documento no vigente o suspendido'
        END AS mensaje_validacion
    FROM verificacion_externa ve
    JOIN certificacion_emitida ce
        ON ve.id_certificacion = ce.id_certificacion
    JOIN asambleista a
        ON ce.id_asambleista = a.id_asambleista
    WHERE ve.codigo_verificacion = p_codigo_verificacion;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_preparar_certificacion
BEFORE INSERT ON certificacion_emitida
FOR EACH ROW
EXECUTE FUNCTION fn_preparar_certificacion();

CREATE TRIGGER tg_crear_verificacion_certificacion
AFTER INSERT ON certificacion_emitida
FOR EACH ROW
EXECUTE FUNCTION fn_crear_verificacion_certificacion();

-- =====================================================
-- 7. DATOS INICIALES
-- =====================================================

INSERT INTO control_folio (anio, ultimo_numero, prefijo)
VALUES
(EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER, 0, 'DAIR')
ON CONFLICT (anio, prefijo) DO NOTHING;

-- =====================================================
-- VISTAS
-- =====================================================

CREATE OR REPLACE VIEW v_certificacion_datos_consolidados AS
SELECT
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    a.correo_institucional,

    COUNT(DISTINCT n.id_nombramiento) AS total_nombramientos,
    MIN(n.fecha_inicio) AS primer_periodo_inicio,
    MAX(COALESCE(n.fecha_fin, CURRENT_DATE)) AS ultimo_periodo_fin,

    COUNT(DISTINCT asp.id_asistencia) AS total_asistencias_plenarias,
    COUNT(DISTINCT asc2.id_asistencia_comision) AS total_asistencias_comision,

    COUNT(DISTINCT pp.id_propuesta) AS total_propuestas_como_proponente,
    COUNT(DISTINCT ic.id_comision) AS total_comisiones_integradas,
    COUNT(DISTINCT va.id_voto_asambleista) AS total_votos_registrados,

    JSONB_AGG(DISTINCT JSONB_BUILD_OBJECT(
        'id_nombramiento', n.id_nombramiento,
        'sector', cs.nombre,
        'puesto', cp.nombre_puesto,
        'fecha_inicio', n.fecha_inicio,
        'fecha_fin', n.fecha_fin,
        'estado', n.estado
    )) FILTER (WHERE n.id_nombramiento IS NOT NULL) AS nombramientos,

    JSONB_AGG(DISTINCT JSONB_BUILD_OBJECT(
        'numero_propuesta', p.numero_propuesta,
        'titulo', p.titulo,
        'fecha_presentacion', p.fecha_presentacion
    )) FILTER (WHERE p.id_propuesta IS NOT NULL) AS propuestas,

    JSONB_AGG(DISTINCT JSONB_BUILD_OBJECT(
        'comision', c.nombre_comision,
        'rol', rc.nombre_rol,
        'fecha_ingreso', ic.fecha_ingreso_nombramiento,
        'fecha_fin', ic.fecha_fin_nombramiento
    )) FILTER (WHERE c.id_comision IS NOT NULL) AS comisiones

FROM asambleista a
LEFT JOIN nombramiento n
    ON a.id_asambleista = n.id_asambleista
LEFT JOIN catalogo_sector cs
    ON n.id_sector = cs.id_sector
LEFT JOIN catalogo_puestos cp
    ON n.id_puesto = cp.id_puesto
LEFT JOIN asistencia_sesion_plenaria asp
    ON a.id_asambleista = asp.id_asambleista
LEFT JOIN asistencia_sesion_comision asc2
    ON a.id_asambleista = asc2.id_asambleista
LEFT JOIN proponente_propuesta pp
    ON a.id_asambleista = pp.id_asambleista
LEFT JOIN propuesta p
    ON pp.id_propuesta = p.id_propuesta
LEFT JOIN integrante_comision ic
    ON a.id_asambleista = ic.id_asambleista
LEFT JOIN comision c
    ON ic.id_comision = c.id_comision
LEFT JOIN catalogo_rol_comision rc
    ON ic.id_rol_comision = rc.id_rol_comision
LEFT JOIN voto_asambleista va
    ON a.id_asambleista = va.id_asambleista
GROUP BY
    a.id_asambleista,
    a.cedula,
    a.nombre,
    a.correo_institucional;

CREATE OR REPLACE VIEW v_verificacion_certificacion AS
SELECT
    ce.id_certificacion,
    ce.folio_unico,
    ce.hash_seguridad,
    ce.estado,
    ce.fecha_emision,
    a.cedula,
    a.nombre AS nombre_asambleista,
    ce.url_pdf,
    ve.codigo_verificacion,
    ve.url_verificacion,
    ve.activo AS verificacion_activa,
    ve.veces_verificado,
    ve.ultima_verificacion,
    CASE
        WHEN ce.estado = 'Activa' AND ve.activo = TRUE THEN 'Válida'
        WHEN ce.estado = 'Anulada' THEN 'Anulada'
        ELSE 'No vigente'
    END AS estado_publico
FROM certificacion_emitida ce
JOIN asambleista a
    ON ce.id_asambleista = a.id_asambleista
LEFT JOIN verificacion_externa ve
    ON ce.id_certificacion = ve.id_certificacion;

CREATE OR REPLACE VIEW v_reporte_certificaciones_mensual AS
SELECT
    EXTRACT(YEAR FROM fecha_emision)::INTEGER AS anio,
    EXTRACT(MONTH FROM fecha_emision)::INTEGER AS mes,
    estado,
    COUNT(*) AS total_certificaciones
FROM certificacion_emitida
GROUP BY
    EXTRACT(YEAR FROM fecha_emision),
    EXTRACT(MONTH FROM fecha_emision),
    estado;

-- =====================================================
-- FIN - ISSUE #17
-- =====================================================
