-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 5 - Registro de Sesiones y Memoria de Votación
-- Depende de: propuesta, sys_usuario, elemento_normativo
-- Motor: Supabase / PostgreSQL
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-- =====================================================
-- 1. CATÁLOGOS DE SESIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_tipo_sesion (
    id_tipo_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    quorum_porcentaje NUMERIC(5,2) NOT NULL DEFAULT 50.00,
    requiere_mayoria_calificada BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_quorum_porcentaje
        CHECK (quorum_porcentaje > 0 AND quorum_porcentaje <= 100),

    CONSTRAINT chk_nombre_tipo_sesion_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_modalidad (
    id_tipo_modalidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_nombre_modalidad_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

-- =====================================================
-- 2. SESIONES
-- =====================================================

CREATE TABLE IF NOT EXISTS sesion (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_modalidad INTEGER NOT NULL,
    id_tipo_sesion INTEGER NOT NULL,
    numero_sesion VARCHAR(50) UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME,
    hora_fin TIME,
    link_acta VARCHAR(500),
    quorum_requerido INTEGER,
    total_asambleistas INTEGER,
    estado VARCHAR(30) DEFAULT 'Programada',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER,

    CONSTRAINT fk_sesion_modalidad
        FOREIGN KEY (id_tipo_modalidad)
        REFERENCES catalogo_tipo_modalidad(id_tipo_modalidad)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesion_tipo
        FOREIGN KEY (id_tipo_sesion)
        REFERENCES catalogo_tipo_sesion(id_tipo_sesion)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesion_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_sesion
        CHECK (estado IN ('Programada', 'En Curso', 'Finalizada', 'Cancelada')),

    CONSTRAINT chk_numero_sesion_no_vacio
        CHECK (BTRIM(numero_sesion) <> ''),

    CONSTRAINT chk_horas_sesion
        CHECK (hora_fin IS NULL OR hora_inicio IS NULL OR hora_fin >= hora_inicio),

    CONSTRAINT chk_totales_sesion
        CHECK (total_asambleistas IS NULL OR total_asambleistas >= 0),

    CONSTRAINT chk_quorum_requerido_sesion
        CHECK (quorum_requerido IS NULL OR quorum_requerido >= 0)
);

-- =====================================================
-- 3. ACTAS
-- =====================================================

CREATE TABLE IF NOT EXISTS acta (
    id_acta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    numero_acta VARCHAR(50) UNIQUE NOT NULL,
    fecha_aprobacion DATE,
    url_documento VARCHAR(500),
    contenido_resumen TEXT,
    observaciones TEXT,
    estado VARCHAR(30) DEFAULT 'Borrador',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER,

    CONSTRAINT fk_acta_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_acta_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_acta
        CHECK (estado IN ('Borrador', 'En Revision', 'Aprobada', 'Publicada')),

    CONSTRAINT chk_numero_acta_no_vacio
        CHECK (BTRIM(numero_acta) <> '')
);

-- =====================================================
-- 4. AGENDA DE SESIÓN PLENARIA
-- =====================================================

CREATE TABLE IF NOT EXISTS punto_agenda_sesion (
    id_punto_agenda_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    id_propuesta INTEGER,
    orden INTEGER NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,

    CONSTRAINT fk_punto_agenda_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_punto_agenda_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT uq_orden_agenda_sesion
        UNIQUE (id_sesion, orden),

    CONSTRAINT chk_orden_agenda_sesion
        CHECK (orden > 0),

    CONSTRAINT chk_titulo_agenda_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

-- =====================================================
-- 5. MEMORIA DE VOTACIÓN
-- Resumen de votos por moción/propuesta discutida.
-- El detalle nominal/anónimo puede ampliarse en Issue 12.
-- =====================================================

CREATE TABLE IF NOT EXISTS votacion (
    id_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    id_propuesta INTEGER,
    id_elemento_normativo INTEGER,
    numero_votacion VARCHAR(50),
    tipo_votacion VARCHAR(30) DEFAULT 'Publica',
    votos_favor INTEGER DEFAULT 0,
    votos_contra INTEGER DEFAULT 0,
    votos_abstencion INTEGER DEFAULT 0,
    total_votantes INTEGER DEFAULT 0,
    resultado VARCHAR(30) DEFAULT 'Pendiente',
    estado_acuerdo VARCHAR(30) DEFAULT 'Borrador',
    fecha_firma_acuerdo TIMESTAMP,
    id_usuario_firma INTEGER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_votacion_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_votacion_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT fk_votacion_elemento_normativo
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE SET NULL,

    CONSTRAINT fk_votacion_usuario_firma
        FOREIGN KEY (id_usuario_firma)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_tipo_votacion
        CHECK (tipo_votacion IN ('Publica', 'Secreta')),

    CONSTRAINT chk_resultado_votacion
        CHECK (resultado IN ('Aprobada', 'Rechazada', 'Empate', 'Pendiente')),

    CONSTRAINT chk_estado_acuerdo
        CHECK (estado_acuerdo IN ('Borrador', 'Firmado', 'Anulado')),

    CONSTRAINT chk_votos_no_negativos
        CHECK (
            votos_favor >= 0
            AND votos_contra >= 0
            AND votos_abstencion >= 0
            AND total_votantes >= 0
        )
);

-- =====================================================
-- 6. BITÁCORA DE ESTADO DE ACUERDO
-- =====================================================

CREATE TABLE IF NOT EXISTS bitacora_estado_votacion (
    id_bitacora_estado_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_votacion INTEGER NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo VARCHAR(30) NOT NULL,
    id_usuario INTEGER,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,

    CONSTRAINT fk_bitacora_votacion
        FOREIGN KEY (id_votacion)
        REFERENCES votacion(id_votacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_bitacora_votacion_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL
);

-- =====================================================
-- 7. ÍNDICES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_sesion_fecha ON sesion(fecha);
CREATE INDEX IF NOT EXISTS idx_sesion_estado ON sesion(estado);
CREATE INDEX IF NOT EXISTS idx_sesion_tipo ON sesion(id_tipo_sesion);
CREATE INDEX IF NOT EXISTS idx_acta_sesion ON acta(id_sesion);
CREATE INDEX IF NOT EXISTS idx_punto_agenda_sesion ON punto_agenda_sesion(id_sesion);
CREATE INDEX IF NOT EXISTS idx_punto_agenda_propuesta ON punto_agenda_sesion(id_propuesta);
CREATE INDEX IF NOT EXISTS idx_votacion_sesion ON votacion(id_sesion);
CREATE INDEX IF NOT EXISTS idx_votacion_propuesta ON votacion(id_propuesta);
CREATE INDEX IF NOT EXISTS idx_votacion_resultado ON votacion(resultado);
CREATE INDEX IF NOT EXISTS idx_votacion_estado_acuerdo ON votacion(estado_acuerdo);

-- =====================================================
-- 8. FUNCIONES Y TRIGGERS
-- =====================================================

CREATE OR REPLACE FUNCTION fn_validar_resumen_votacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.total_votantes :=
        COALESCE(NEW.votos_favor, 0)
        + COALESCE(NEW.votos_contra, 0)
        + COALESCE(NEW.votos_abstencion, 0);

    IF NEW.estado_acuerdo = 'Firmado' AND NEW.fecha_firma_acuerdo IS NULL THEN
        NEW.fecha_firma_acuerdo := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_bitacora_estado_votacion()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.estado_acuerdo <> NEW.estado_acuerdo THEN
        INSERT INTO bitacora_estado_votacion (
            id_votacion,
            estado_anterior,
            estado_nuevo,
            id_usuario,
            observaciones
        )
        VALUES (
            NEW.id_votacion,
            OLD.estado_acuerdo,
            NEW.estado_acuerdo,
            NEW.id_usuario_firma,
            'Cambio automático de estado de acuerdo'
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_resumen_votacion
BEFORE INSERT OR UPDATE ON votacion
FOR EACH ROW
EXECUTE FUNCTION fn_validar_resumen_votacion();

CREATE TRIGGER tg_bitacora_estado_votacion
AFTER UPDATE ON votacion
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_estado_votacion();

-- =====================================================
-- 9. VISTAS
-- =====================================================

CREATE OR REPLACE VIEW v_memoria_votacion_sesion AS
SELECT
    v.id_votacion,
    s.id_sesion,
    s.numero_sesion,
    s.fecha,
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    v.numero_votacion,
    v.tipo_votacion,
    v.votos_favor,
    v.votos_contra,
    v.votos_abstencion,
    v.total_votantes,
    v.resultado,
    v.estado_acuerdo,
    v.fecha_firma_acuerdo
FROM votacion v
JOIN sesion s ON v.id_sesion = s.id_sesion
LEFT JOIN propuesta p ON v.id_propuesta = p.id_propuesta;

-- =====================================================
-- 10. DATOS INICIALES
-- =====================================================

INSERT INTO catalogo_tipo_sesion
(id_tipo_sesion, nombre, descripcion, quorum_porcentaje, requiere_mayoria_calificada)
VALUES
(1, 'Ordinaria', 'Sesión regular programada en el calendario', 50.00, FALSE),
(2, 'Extraordinaria', 'Sesión convocada fuera del calendario ordinario', 66.00, TRUE),
(3, 'Solemne', 'Sesión protocolaria o conmemorativa', 33.00, FALSE)
ON CONFLICT (id_tipo_sesion) DO NOTHING;

INSERT INTO catalogo_tipo_modalidad
(id_tipo_modalidad, nombre, descripcion)
VALUES
(1, 'Presencial', 'Sesión realizada en el recinto de la AIR'),
(2, 'Virtual', 'Sesión realizada por videoconferencia'),
(3, 'Mixta', 'Combinación de presencial y virtual')
ON CONFLICT (id_tipo_modalidad) DO NOTHING;
