-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 5 - Sesiones y Memoria de Votación
-- Autora: María Fernanda Vargas Guzmán
-- Depende de: asambleista (issue 9) y propuesta (issue 10) 
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::


-- ....................
-- Nuevo catálogo
-- ....................
CREATE TABLE IF NOT EXISTS catalogo_tipo_voto (
    id_tipo_voto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20) UNIQUE NOT NULL,
    descripcion TEXT
);


-- ....................
-- 1. Tabla sesion
-- ....................

CREATE TABLE IF NOT EXISTS sesion (
    id_sesion BIGSERIAL PRIMARY KEY,
    numero_sesion VARCHAR(50) NOT NULL UNIQUE,
    tipo_sesion VARCHAR(30) NOT NULL,
    fecha DATE NOT NULL,
    quorum_requerido INTEGER NOT NULL DEFAULT 0,
    quorum_cumplido BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_tipo_sesion
        CHECK (tipo_sesion IN ('Ordinaria', 'Extraordinaria'))
);


-- .............................
-- 2. Tabla asistencia_sesion
-- .............................

CREATE TABLE IF NOT EXISTS asistencia_sesion (
    id_asistencia BIGSERIAL PRIMARY KEY,
    id_sesion BIGINT NOT NULL,
    asambleista_id BIGINT NOT NULL,
    presente BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asistencia_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_asambleista
        FOREIGN KEY (asambleista_id)
        REFERENCES asambleista(asambleista_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_asistencia_sesion_asambleista
        UNIQUE (id_sesion, asambleista_id)
);


-- ......................
-- 3. Tabla votación
-- ......................

CREATE TABLE IF NOT EXISTS votacion (
    id_votacion BIGSERIAL PRIMARY KEY,
    id_sesion BIGINT NOT NULL,
    id_propuesta BIGINT NOT NULL,
    asambleista_id BIGINT NOT NULL,
    id_tipo_voto INTEGER NOT NULL,
    fecha_voto TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_votacion_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_votacion_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE CASCADE,

    CONSTRAINT fk_votacion_asambleista
        FOREIGN KEY (asambleista_id)
        REFERENCES asambleista(asambleista_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_votacion_tipo_voto
        FOREIGN KEY (id_tipo_voto)
        REFERENCES catalogo_tipo_voto(id_tipo_voto),

    CONSTRAINT uq_voto_por_asambleista
        UNIQUE (id_sesion, id_propuesta, asambleista_id)
);
