-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 11 - Control de Quórum y Sesiones
-- Depende de: asambleista, nombramiento, sys_usuario
-- Requiere: catalogo_estado_asistencia (Issue #7, va antes que este bloque)
-- Motor: Supabase / PostgreSQL
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-- =====================================================
-- 1. CATÁLOGO DE TIPOS DE SESIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_tipo_sesion (
    id_tipo_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    quorum_porcentaje NUMERIC(5,2) NOT NULL DEFAULT 50.00,
    requiere_mayoria_calificada BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_quorum_porcentaje
        CHECK (quorum_porcentaje > 0 AND quorum_porcentaje <= 100),

    CONSTRAINT chk_nombre_tipo_sesion_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

-- =====================================================
-- 2. CATÁLOGO DE MODALIDADES
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_tipo_modalidad (
    id_tipo_modalidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_nombre_modalidad_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

-- =====================================================
-- 3. SESIONES
-- =====================================================

CREATE TABLE IF NOT EXISTS sesion (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_modalidad INTEGER NOT NULL,
    id_tipo_sesion INTEGER NOT NULL,
    numero_sesion VARCHAR(50) UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME,
    hora_fin TIME,
    link_acta VARCHAR(500),
    quorum_requerido INTEGER,
    total_asambleistas INTEGER,
    estado VARCHAR(30) DEFAULT 'Programada',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER,

    CONSTRAINT fk_sesion_modalidad
        FOREIGN KEY (id_tipo_modalidad)
        REFERENCES catalogo_tipo_modalidad(id_tipo_modalidad)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesion_tipo
        FOREIGN KEY (id_tipo_sesion)
        REFERENCES catalogo_tipo_sesion(id_tipo_sesion)
        ON DELETE RESTRICT,

    CONSTRAINT fk_sesion_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_sesion
        CHECK (estado IN ('Programada', 'En Curso', 'Finalizada', 'Cancelada')),

    CONSTRAINT chk_numero_sesion_no_vacio
        CHECK (BTRIM(numero_sesion) <> ''),

    CONSTRAINT chk_horas_sesion
        CHECK (hora_fin IS NULL OR hora_inicio IS NULL OR hora_fin >= hora_inicio),

    CONSTRAINT chk_totales_sesion
        CHECK (total_asambleistas IS NULL OR total_asambleistas >= 0),

    CONSTRAINT chk_quorum_requerido_sesion
        CHECK (quorum_requerido IS NULL OR quorum_requerido >= 0)
);

-- =====================================================
-- 4. ACTAS
-- =====================================================

CREATE TABLE IF NOT EXISTS acta (
    id_acta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    numero_acta VARCHAR(50) UNIQUE NOT NULL,
    fecha_aprobacion DATE,
    url_documento VARCHAR(500),
    contenido_resumen TEXT,
    observaciones TEXT,
    estado VARCHAR(30) DEFAULT 'Borrador',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario_registro INTEGER,

    CONSTRAINT fk_acta_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_acta_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_estado_acta
        CHECK (estado IN ('Borrador', 'En Revision', 'Aprobada', 'Publicada')),

    CONSTRAINT chk_numero_acta_no_vacio
        CHECK (BTRIM(numero_acta) <> '')
);

-- =====================================================
-- 5. ASISTENCIA DE SESIONES PLENARIAS
-- =====================================================

CREATE TABLE IF NOT EXISTS asistencia_sesion_plenaria (
    id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    id_sesion INTEGER NOT NULL,
    id_estado_asistencia INTEGER NOT NULL,
    hora_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT,

    CONSTRAINT fk_asistencia_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_estado
        FOREIGN KEY (id_estado_asistencia)
        REFERENCES catalogo_estado_asistencia(id_estado_asistencia)
        ON DELETE RESTRICT,

    CONSTRAINT uq_asistencia_sesion
        UNIQUE (id_asambleista, id_sesion)
);

-- =====================================================
-- 6. VOTACIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS votacion (
    id_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    id_propuesta INTEGER,
    id_elemento_normativo INTEGER,
    numero_votacion VARCHAR(50),
    tipo_votacion VARCHAR(30) DEFAULT 'Publica',
    votos_favor INTEGER DEFAULT 0,
    votos_contra INTEGER DEFAULT 0,
    votos_abstencion INTEGER DEFAULT 0,
    total_votantes INTEGER DEFAULT 0,
    resultado VARCHAR(30) DEFAULT 'Pendiente',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_votacion_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT fk_votacion_elemento_normativo
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE SET NULL,

    CONSTRAINT chk_tipo_votacion
        CHECK (tipo_votacion IN ('Publica', 'Secreta')),

    CONSTRAINT chk_resultado_votacion
        CHECK (resultado IN ('Aprobada', 'Rechazada', 'Empate', 'Pendiente')),

    CONSTRAINT chk_votos_no_negativos
        CHECK (
            votos_favor >= 0
            AND votos_contra >= 0
            AND votos_abstencion >= 0
            AND total_votantes >= 0
        )
);

-- =====================================================
-- 7. ÍNDICES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_sesion_fecha ON sesion(fecha);
CREATE INDEX IF NOT EXISTS idx_sesion_estado ON sesion(estado);
CREATE INDEX IF NOT EXISTS idx_asistencia_sesion ON asistencia_sesion_plenaria(id_sesion);
CREATE INDEX IF NOT EXISTS idx_asistencia_asambleista ON asistencia_sesion_plenaria(id_asambleista);
CREATE INDEX IF NOT EXISTS idx_acta_sesion ON acta(id_sesion);
CREATE INDEX IF NOT EXISTS idx_votacion_sesion ON votacion(id_sesion);

-- =====================================================
-- 8. FUNCIONES DE QUÓRUM
-- =====================================================

CREATE OR REPLACE FUNCTION fn_total_asambleistas_activos(p_fecha DATE)
RETURNS INTEGER AS $$
DECLARE
    v_total INTEGER;
BEGIN
    SELECT COUNT(DISTINCT n.id_asambleista)
    INTO v_total
    FROM nombramiento n
    WHERE n.estado = 'Activo'
      AND n.fecha_inicio <= p_fecha
      AND COALESCE(n.fecha_fin, DATE '9999-12-31') >= p_fecha;

    RETURN COALESCE(v_total, 0);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_asistentes_para_quorum(p_id_sesion INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_total INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO v_total
    FROM asistencia_sesion_plenaria asp
    INNER JOIN catalogo_estado_asistencia cea
        ON asp.id_estado_asistencia = cea.id_estado_asistencia
    WHERE asp.id_sesion = p_id_sesion
      AND cea.nombre IN ('Presente', 'Retardo');

    RETURN COALESCE(v_total, 0);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_quorum_requerido(p_id_sesion INTEGER)
RETURNS INTEGER AS $$
DECLARE
    v_total_asambleistas INTEGER;
    v_porcentaje NUMERIC(5,2);
    v_requerido INTEGER;
BEGIN
    SELECT
        COALESCE(s.total_asambleistas, fn_total_asambleistas_activos(s.fecha)),
        cts.quorum_porcentaje
    INTO v_total_asambleistas, v_porcentaje
    FROM sesion s
    INNER JOIN catalogo_tipo_sesion cts
        ON s.id_tipo_sesion = cts.id_tipo_sesion
    WHERE s.id_sesion = p_id_sesion;

    IF v_total_asambleistas IS NULL OR v_total_asambleistas = 0 THEN
        RAISE EXCEPTION 'No se puede calcular quórum: no hay asambleístas activos para la fecha de la sesión.';
    END IF;

    v_requerido := CEIL(v_total_asambleistas * (v_porcentaje / 100.0));

    RETURN v_requerido;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_quorum(p_id_sesion INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
    v_presentes INTEGER;
    v_requerido INTEGER;
BEGIN
    v_presentes := fn_asistentes_para_quorum(p_id_sesion);
    v_requerido := fn_quorum_requerido(p_id_sesion);

    RETURN v_presentes >= v_requerido;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- 9. FUNCIÓN PARA CALCULAR RESULTADO DE VOTACIÓN
-- =====================================================

CREATE OR REPLACE FUNCTION fn_calcular_resultado_votacion(
    p_votos_favor INTEGER,
    p_votos_contra INTEGER,
    p_tipo_mayoria VARCHAR
)
RETURNS VARCHAR AS $$
DECLARE
    v_total INTEGER;
    v_umbral NUMERIC;
BEGIN
    v_total := p_votos_favor + p_votos_contra;

    IF v_total = 0 THEN
        RETURN 'Pendiente';
    END IF;

    IF p_tipo_mayoria = 'Calificada' THEN
        v_umbral := v_total * (2.0 / 3.0);
        IF p_votos_favor >= CEIL(v_umbral) THEN
            RETURN 'Aprobada';
        ELSE
            RETURN 'Rechazada';
        END IF;
    ELSE
        IF p_votos_favor > p_votos_contra THEN
            RETURN 'Aprobada';
        ELSIF p_votos_favor = p_votos_contra THEN
            RETURN 'Empate';
        ELSE
            RETURN 'Rechazada';
        END IF;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- 10. TRIGGER: ACTUALIZAR RESUMEN DE QUÓRUM EN SESIÓN
-- =====================================================

CREATE OR REPLACE FUNCTION fn_actualizar_resumen_quorum()
RETURNS TRIGGER AS $$
DECLARE
    v_id_sesion INTEGER;
    v_total INTEGER;
    v_requerido INTEGER;
BEGIN
    v_id_sesion := COALESCE(NEW.id_sesion, OLD.id_sesion);

    SELECT fn_total_asambleistas_activos(fecha)
    INTO v_total
    FROM sesion
    WHERE id_sesion = v_id_sesion;

    v_requerido := fn_quorum_requerido(v_id_sesion);

    UPDATE sesion
    SET total_asambleistas = v_total,
        quorum_requerido   = v_requerido
    WHERE id_sesion = v_id_sesion;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_actualizar_resumen_quorum
AFTER INSERT OR UPDATE OR DELETE ON asistencia_sesion_plenaria
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_resumen_quorum();

-- =====================================================
-- 11. TRIGGER: BLOQUEAR VOTACIÓN SIN QUÓRUM
-- =====================================================

CREATE OR REPLACE FUNCTION fn_bloquear_votacion_sin_quorum()
RETURNS TRIGGER AS $$
DECLARE
    v_presentes INTEGER;
    v_requerido INTEGER;
BEGIN
    v_presentes := fn_asistentes_para_quorum(NEW.id_sesion);
    v_requerido := fn_quorum_requerido(NEW.id_sesion);

    IF v_presentes < v_requerido THEN
        RAISE EXCEPTION
            'Quórum insuficiente. Presentes: %, requeridos: %. No se puede registrar la votación.',
            v_presentes,
            v_requerido;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_quorum
BEFORE INSERT OR UPDATE ON votacion
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_votacion_sin_quorum();

-- =====================================================
-- 12. VISTA DE ESTADO DE QUÓRUM
-- =====================================================

CREATE OR REPLACE VIEW v_estado_quorum_sesion AS
SELECT
    s.id_sesion,
    s.numero_sesion,
    s.fecha,
    cts.nombre AS tipo_sesion,
    cts.quorum_porcentaje,
    COALESCE(s.total_asambleistas, fn_total_asambleistas_activos(s.fecha)) AS total_asambleistas,
    fn_asistentes_para_quorum(s.id_sesion) AS presentes_para_quorum,
    fn_quorum_requerido(s.id_sesion) AS quorum_requerido,
    CASE
        WHEN fn_validar_quorum(s.id_sesion) THEN 'Quórum válido'
        ELSE 'Quórum insuficiente'
    END AS estado_quorum
FROM sesion s
INNER JOIN catalogo_tipo_sesion cts
    ON s.id_tipo_sesion = cts.id_tipo_sesion;

-- =====================================================
-- 13. DATOS INICIALES
-- =====================================================

INSERT INTO catalogo_tipo_sesion
    (id_tipo_sesion, nombre, descripcion, quorum_porcentaje, requiere_mayoria_calificada)
VALUES
    (1, 'Ordinaria',      'Sesión regular programada en el calendario',      50.00, FALSE),
    (2, 'Extraordinaria', 'Sesión convocada fuera del calendario ordinario',  66.00, TRUE),
    (3, 'Solemne',        'Sesión protocolaria o conmemorativa',              33.00, FALSE)
ON CONFLICT (id_tipo_sesion) DO NOTHING;

INSERT INTO catalogo_tipo_modalidad
    (id_tipo_modalidad, nombre, descripcion)
VALUES
    (1, 'Presencial', 'Sesión realizada en el recinto de la AIR'),
    (2, 'Virtual',    'Sesión realizada por videoconferencia'),
    (3, 'Mixta',      'Combinación de presencial y virtual')
ON CONFLICT (id_tipo_modalidad) DO NOTHING;

-- Presente=1, Ausente=2, Justificado=3 ya fueron insertados por Issue #7
INSERT INTO catalogo_estado_asistencia
    (id_estado_asistencia, nombre, descripcion)
VALUES
    (4, 'Retardo', 'Llegó tarde pero participa en la sesión')
ON CONFLICT (id_estado_asistencia) DO NOTHING;

-- Reiniciar secuencias
SELECT setval(pg_get_serial_sequence('catalogo_tipo_sesion', 'id_tipo_sesion'), COALESCE(MAX(id_tipo_sesion), 1)) FROM catalogo_tipo_sesion;
SELECT setval(pg_get_serial_sequence('catalogo_tipo_modalidad', 'id_tipo_modalidad'), COALESCE(MAX(id_tipo_modalidad), 1)) FROM catalogo_tipo_modalidad;
SELECT setval(pg_get_serial_sequence('catalogo_estado_asistencia', 'id_estado_asistencia'), COALESCE(MAX(id_estado_asistencia), 1)) FROM catalogo_estado_asistencia;

-- =====================================================
-- 14. ALTER TABLE DIFERIDO
-- =====================================================

ALTER TABLE votacion
    ADD CONSTRAINT fk_votacion_propuesta
    FOREIGN KEY (id_propuesta)
    REFERENCES propuesta(id_propuesta)
    ON DELETE SET NULL;

-- =====================================================
-- FIN - ISSUE #11
-- =====================================================
