-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 7 - Gestión de Comisiones de Análisis
-- Autora: María Fernanda Vargas Guzmán
-- Depende de: asambleista (issue 9), propuesta (issue 10) y sesion (issue 5)
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


-- ......................
-- Nuevos Catálogos
-- ......................

CREATE TABLE IF NOT EXISTS catalogo_tipo_comision (
    id_tipo_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS catalogo_rol_comision (
    id_rol_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_tramite (
    id_tipo_tramite INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS catalogo_estado_asistencia (
    id_estado_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);


-- .............................
-- Tabla comisión
-- .............................

CREATE TABLE IF NOT EXISTS comision (
    id_comision BIGSERIAL PRIMARY KEY,
    id_tipo_comision INTEGER NOT NULL,
    nombre_comision VARCHAR(150) NOT NULL,
    objeto TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_comision_tipo
        FOREIGN KEY (id_tipo_comision)
        REFERENCES catalogo_tipo_comision(id_tipo_comision)
        ON DELETE RESTRICT
);


-- .............................
-- Tabla proposito_comision
-- .............................

CREATE TABLE IF NOT EXISTS proposito_comision (
    id_proposito_comision BIGSERIAL PRIMARY KEY,
    id_comision BIGINT NOT NULL,
    id_propuesta BIGINT NOT NULL,
    texto TEXT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_proposito_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_proposito_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE RESTRICT
);


-- .............................
-- Tabla integrante_comision
-- .............................

CREATE TABLE IF NOT EXISTS integrante_comision (
    id_integrante_comision BIGSERIAL PRIMARY KEY,
    id_comision BIGINT NOT NULL,
    asambleista_id BIGINT NOT NULL,
    id_rol_comision INTEGER NOT NULL,
    fecha_ingreso_nombramiento DATE NOT NULL,
    fecha_fin_nombramiento DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',

    CONSTRAINT fk_integrante_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_integrante_asambleista
        FOREIGN KEY (asambleista_id)
        REFERENCES asambleista(asambleista_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_integrante_rol
        FOREIGN KEY (id_rol_comision)
        REFERENCES catalogo_rol_comision(id_rol_comision)
        ON DELETE RESTRICT,

    CONSTRAINT chk_estado_integrante
        CHECK (estado IN ('Activo', 'Inactivo')),

    CONSTRAINT chk_fechas_integrante
        CHECK (fecha_fin_nombramiento IS NULL OR fecha_fin_nombramiento >= fecha_ingreso_nombramiento)
);


-- .............................
-- Tabla sesion_comision
-- .............................

CREATE TABLE IF NOT EXISTS sesion_comision (
    id_sesion_comision BIGSERIAL PRIMARY KEY,
    id_comision BIGINT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    observaciones TEXT,

    CONSTRAINT fk_sesion_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE
);


-- ....................................
-- Tabla punto_agenda_sesion_comision
-- ....................................

CREATE TABLE IF NOT EXISTS punto_agenda_sesion_comision (
    id_punto_agenda_sesion_comision BIGSERIAL PRIMARY KEY,
    id_sesion_comision BIGINT NOT NULL,
    id_proposito_comision BIGINT NOT NULL,
    id_tipo_tramite INTEGER NOT NULL,
    orden INTEGER NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,

    CONSTRAINT fk_punto_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_punto_proposito
        FOREIGN KEY (id_proposito_comision)
        REFERENCES proposito_comision(id_proposito_comision)
        ON DELETE RESTRICT,

    CONSTRAINT fk_punto_tipo_tramite
        FOREIGN KEY (id_tipo_tramite)
        REFERENCES catalogo_tipo_tramite(id_tipo_tramite)
        ON DELETE RESTRICT,

    CONSTRAINT uq_orden_sesion_comision
        UNIQUE (id_sesion_comision, orden),

    CONSTRAINT chk_orden_punto_comision
        CHECK (orden > 0)
);


-- .............................
-- Tabla informe_directorio
-- .............................

CREATE TABLE IF NOT EXISTS informe_directorio (
    id_informe BIGSERIAL PRIMARY KEY,
    id_comision BIGINT NOT NULL,
    id_propuesta BIGINT NOT NULL,
    id_sesion BIGINT,
    titulo VARCHAR(200) NOT NULL,
    recomendacion TEXT,
    fecha_presentacion DATE,

    CONSTRAINT fk_informe_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE RESTRICT,

    CONSTRAINT fk_informe_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_informe_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES sesion(id_sesion)
        ON DELETE SET NULL
);


-- ..................................
-- Tabla asistencia_sesion_comision
-- ..................................

CREATE TABLE IF NOT EXISTS asistencia_sesion_comision (
    id_asistencia_comision BIGSERIAL PRIMARY KEY,
    asambleista_id BIGINT NOT NULL,
    id_sesion_comision BIGINT NOT NULL,
    id_comision BIGINT NOT NULL,
    id_estado_asistencia INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asistencia_comision_asambleista
        FOREIGN KEY (asambleista_id)
        REFERENCES asambleista(asambleista_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asistencia_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_estado
        FOREIGN KEY (id_estado_asistencia)
        REFERENCES catalogo_estado_asistencia(id_estado_asistencia)
        ON DELETE RESTRICT,

    CONSTRAINT uq_asistencia_comision
        UNIQUE (asambleista_id, id_sesion_comision)
);
