-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 12 - Motor de Votaciones
-- Complemento del Sistema de Votaciones
-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-- =========================
-- CATÁLOGOS
-- =========================

CREATE TABLE IF NOT EXISTS catalogo_tipo_mayoria_requerida (
    id_tipo_mayoria_requerida INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    porcentaje_requerido NUMERIC(5,2) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_porcentaje_mayoria
        CHECK (porcentaje_requerido > 0 AND porcentaje_requerido <= 100),

    CONSTRAINT chk_nombre_mayoria_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_votacion (
    id_tipo_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_nombre_tipo_votacion_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

-- =========================
-- TABLAS
-- =========================

CREATE TABLE IF NOT EXISTS resultado_votacion (
    id_resultado_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_votacion INTEGER NOT NULL UNIQUE,
    id_tipo_mayoria_requerida INTEGER NOT NULL,
    id_tipo_votacion INTEGER NOT NULL,
    total_presentes INTEGER NOT NULL DEFAULT 0,
    total_votos INTEGER NOT NULL DEFAULT 0,
    votos_favor INTEGER NOT NULL DEFAULT 0,
    votos_contra INTEGER NOT NULL DEFAULT 0,
    abstenciones INTEGER NOT NULL DEFAULT 0,
    porcentaje_aprobacion NUMERIC(5,2),
    resultado VARCHAR(30) NOT NULL DEFAULT 'Pendiente',
    fecha_apertura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP,

    CONSTRAINT fk_resultado_votacion
        FOREIGN KEY (id_votacion)
        REFERENCES votacion(id_votacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_resultado_mayoria
        FOREIGN KEY (id_tipo_mayoria_requerida)
        REFERENCES catalogo_tipo_mayoria_requerida(id_tipo_mayoria_requerida)
        ON DELETE RESTRICT,

    CONSTRAINT fk_resultado_tipo_votacion
        FOREIGN KEY (id_tipo_votacion)
        REFERENCES catalogo_tipo_votacion(id_tipo_votacion)
        ON DELETE RESTRICT,

    CONSTRAINT chk_resultado_motor_votacion
        CHECK (resultado IN ('Aprobada', 'Rechazada', 'Pendiente', 'Anulada')),

    CONSTRAINT chk_conteos_resultado_no_negativos
        CHECK (
            total_presentes >= 0
            AND total_votos >= 0
            AND votos_favor >= 0
            AND votos_contra >= 0
            AND abstenciones >= 0
        ),

    CONSTRAINT chk_fechas_resultado_votacion
        CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_apertura)
);

CREATE TABLE IF NOT EXISTS voto_asambleista (
    id_voto_asambleista INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_votacion INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    id_tipo_voto INTEGER NOT NULL,
    codigo_voto_anonimo VARCHAR(64) DEFAULT MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT),
    fecha_voto TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_voto_votacion
        FOREIGN KEY (id_votacion)
        REFERENCES votacion(id_votacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_voto_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_voto_tipo
        FOREIGN KEY (id_tipo_voto)
        REFERENCES catalogo_tipo_voto(id_tipo_voto)
        ON DELETE RESTRICT,

    CONSTRAINT uq_voto_asambleista
        UNIQUE (id_votacion, id_asambleista)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_resultado_votacion ON resultado_votacion(id_votacion);
CREATE INDEX IF NOT EXISTS idx_resultado_mayoria ON resultado_votacion(id_tipo_mayoria_requerida);
CREATE INDEX IF NOT EXISTS idx_voto_asambleista_votacion ON voto_asambleista(id_votacion);
CREATE INDEX IF NOT EXISTS idx_voto_asambleista_asambleista ON voto_asambleista(id_asambleista);
CREATE INDEX IF NOT EXISTS idx_voto_asambleista_tipo ON voto_asambleista(id_tipo_voto);

-- =========================
-- FUNCIONES Y TRIGGERS
-- =========================
CREATE OR REPLACE FUNCTION fn_calcular_resultado_votacion_detalle(
    p_votos_favor INTEGER,
    p_votos_contra INTEGER,
    p_total_presentes INTEGER,
    p_tipo_mayoria VARCHAR
)
RETURNS VARCHAR AS $$
DECLARE
    v_umbral INTEGER;
BEGIN
    IF p_total_presentes IS NULL OR p_total_presentes = 0 THEN
        RETURN 'Pendiente';
    END IF;

    IF p_tipo_mayoria = 'Calificada' THEN
        v_umbral := CEIL(p_total_presentes * 0.6667);

        IF p_votos_favor >= v_umbral THEN
            RETURN 'Aprobada';
        ELSE
            RETURN 'Rechazada';
        END IF;
    ELSE
        IF p_votos_favor > p_votos_contra THEN
            RETURN 'Aprobada';
        ELSE
            RETURN 'Rechazada';
        END IF;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_voto_asambleista()
RETURNS TRIGGER AS $$
DECLARE
    v_id_sesion INTEGER;
BEGIN
    SELECT id_sesion
    INTO v_id_sesion
    FROM votacion
    WHERE id_votacion = NEW.id_votacion;

    IF v_id_sesion IS NULL THEN
        RAISE EXCEPTION 'La votación indicada no existe.';
    END IF;

    IF NOT fn_validar_quorum(v_id_sesion) THEN
        RAISE EXCEPTION 'No se puede registrar el voto porque la sesión no tiene quórum válido.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM resultado_votacion rv
        WHERE rv.id_votacion = NEW.id_votacion
          AND rv.fecha_cierre IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'No se puede votar porque la votación ya está cerrada.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM asistencia_sesion_plenaria asp
        JOIN catalogo_estado_asistencia cea
            ON asp.id_estado_asistencia = cea.id_estado_asistencia
        WHERE asp.id_sesion = v_id_sesion
          AND asp.id_asambleista = NEW.id_asambleista
          AND cea.nombre IN ('Presente', 'Retardo')
    ) THEN
        RAISE EXCEPTION 'Solo pueden votar asambleístas presentes o con retardo registrado.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_recalcular_resultado_votacion(p_id_votacion INTEGER)
RETURNS VOID AS $$
DECLARE
    v_id_sesion INTEGER;
    v_total_presentes INTEGER;
    v_total_votos INTEGER;
    v_favor INTEGER;
    v_contra INTEGER;
    v_abstenciones INTEGER;
    v_porcentaje NUMERIC(5,2);
    v_tipo_mayoria VARCHAR(50);
    v_id_tipo_mayoria INTEGER;
    v_id_tipo_votacion INTEGER;
    v_resultado VARCHAR(30);
BEGIN
    SELECT id_sesion
    INTO v_id_sesion
    FROM votacion
    WHERE id_votacion = p_id_votacion;

    IF v_id_sesion IS NULL THEN
        RETURN;
    END IF;

    v_total_presentes := fn_asistentes_para_quorum(v_id_sesion);

    SELECT COUNT(*)
    INTO v_total_votos
    FROM voto_asambleista
    WHERE id_votacion = p_id_votacion;

    SELECT COUNT(*)
    INTO v_favor
    FROM voto_asambleista va
    JOIN catalogo_tipo_voto ctv ON va.id_tipo_voto = ctv.id_tipo_voto
    WHERE va.id_votacion = p_id_votacion
      AND ctv.nombre = 'Favor';

    SELECT COUNT(*)
    INTO v_contra
    FROM voto_asambleista va
    JOIN catalogo_tipo_voto ctv ON va.id_tipo_voto = ctv.id_tipo_voto
    WHERE va.id_votacion = p_id_votacion
      AND ctv.nombre = 'Contra';

    SELECT COUNT(*)
    INTO v_abstenciones
    FROM voto_asambleista va
    JOIN catalogo_tipo_voto ctv ON va.id_tipo_voto = ctv.id_tipo_voto
    WHERE va.id_votacion = p_id_votacion
      AND ctv.nombre = 'Abstención';

    SELECT
        COALESCE(rv.id_tipo_mayoria_requerida, 1),
        COALESCE(rv.id_tipo_votacion, 1),
        cm.nombre
    INTO v_id_tipo_mayoria, v_id_tipo_votacion, v_tipo_mayoria
    FROM resultado_votacion rv
    JOIN catalogo_tipo_mayoria_requerida cm
        ON rv.id_tipo_mayoria_requerida = cm.id_tipo_mayoria_requerida
    WHERE rv.id_votacion = p_id_votacion;

    IF v_id_tipo_mayoria IS NULL THEN
        v_id_tipo_mayoria := 1;
        v_id_tipo_votacion := 1;
        v_tipo_mayoria := 'Simple';
    END IF;

    IF v_total_presentes = 0 THEN
        v_porcentaje := 0;
    ELSE
        v_porcentaje := ROUND((v_favor::NUMERIC / v_total_presentes::NUMERIC) * 100, 2);
    END IF;

    v_resultado := fn_calcular_resultado_votacion_detalle(
        v_favor,
        v_contra,
        v_total_presentes,
        v_tipo_mayoria
    );

    INSERT INTO resultado_votacion (
        id_votacion,
        id_tipo_mayoria_requerida,
        id_tipo_votacion,
        total_presentes,
        total_votos,
        votos_favor,
        votos_contra,
        abstenciones,
        porcentaje_aprobacion,
        resultado
    )
    VALUES (
        p_id_votacion,
        v_id_tipo_mayoria,
        v_id_tipo_votacion,
        v_total_presentes,
        v_total_votos,
        v_favor,
        v_contra,
        v_abstenciones,
        v_porcentaje,
        v_resultado
    )
    ON CONFLICT (id_votacion) DO UPDATE SET
        total_presentes = EXCLUDED.total_presentes,
        total_votos = EXCLUDED.total_votos,
        votos_favor = EXCLUDED.votos_favor,
        votos_contra = EXCLUDED.votos_contra,
        abstenciones = EXCLUDED.abstenciones,
        porcentaje_aprobacion = EXCLUDED.porcentaje_aprobacion,
        resultado = EXCLUDED.resultado;

    UPDATE votacion
    SET votos_favor = v_favor,
        votos_contra = v_contra,
        votos_abstencion = v_abstenciones,
        total_votantes = v_total_votos,
        resultado = v_resultado
    WHERE id_votacion = p_id_votacion;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_trigger_recalcular_resultado_votacion()
RETURNS TRIGGER AS $$
DECLARE
    v_id_votacion INTEGER;
BEGIN
    v_id_votacion := COALESCE(NEW.id_votacion, OLD.id_votacion);

    PERFORM fn_recalcular_resultado_votacion(v_id_votacion);

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_voto_asambleista
BEFORE INSERT OR UPDATE ON voto_asambleista
FOR EACH ROW
EXECUTE FUNCTION fn_validar_voto_asambleista();

CREATE TRIGGER tg_recalcular_resultado_votacion
AFTER INSERT OR UPDATE OR DELETE ON voto_asambleista
FOR EACH ROW
EXECUTE FUNCTION fn_trigger_recalcular_resultado_votacion();

-- =========================
-- VISTAS
-- =========================
CREATE OR REPLACE VIEW v_resultado_votacion_detalle AS
SELECT
    rv.id_resultado_votacion,
    v.id_votacion,
    s.numero_sesion,
    s.fecha,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    cm.nombre AS tipo_mayoria,
    cm.porcentaje_requerido,
    ctv.nombre AS tipo_votacion,
    rv.total_presentes,
    rv.total_votos,
    rv.votos_favor,
    rv.votos_contra,
    rv.abstenciones,
    rv.porcentaje_aprobacion,
    rv.resultado,
    rv.fecha_apertura,
    rv.fecha_cierre
FROM resultado_votacion rv
JOIN votacion v ON rv.id_votacion = v.id_votacion
JOIN sesion s ON v.id_sesion = s.id_sesion
LEFT JOIN propuesta p ON v.id_propuesta = p.id_propuesta
JOIN catalogo_tipo_mayoria_requerida cm
    ON rv.id_tipo_mayoria_requerida = cm.id_tipo_mayoria_requerida
JOIN catalogo_tipo_votacion ctv
    ON rv.id_tipo_votacion = ctv.id_tipo_votacion;

CREATE OR REPLACE VIEW v_votos_nominales AS
SELECT
    va.id_voto_asambleista,
    va.id_votacion,
    s.numero_sesion,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    tv.nombre AS voto,
    va.fecha_voto
FROM voto_asambleista va
JOIN votacion v ON va.id_votacion = v.id_votacion
JOIN sesion s ON v.id_sesion = s.id_sesion
JOIN asambleista a ON va.id_asambleista = a.id_asambleista
JOIN catalogo_tipo_voto tv ON va.id_tipo_voto = tv.id_tipo_voto
WHERE v.tipo_votacion = 'Publica';

-- =========================
-- DATOS INICIALES
-- =========================
INSERT INTO catalogo_tipo_mayoria_requerida
(id_tipo_mayoria_requerida, nombre, porcentaje_requerido, descripcion)
VALUES
(1, 'Simple', 50.00, 'Mayoría simple: más votos a favor que en contra'),
(2, 'Calificada', 66.67, 'Mayoría calificada: al menos dos tercios de los presentes')
ON CONFLICT (id_tipo_mayoria_requerida) DO NOTHING;

INSERT INTO catalogo_tipo_votacion
(id_tipo_votacion, nombre, descripcion)
VALUES
(1, 'Pública', 'Votación nominal visible'),
(2, 'Secreta', 'Votación anónima para reportes públicos')
ON CONFLICT (id_tipo_votacion) DO NOTHING;

INSERT INTO catalogo_tipo_voto
(id_tipo_voto, nombre, descripcion)
VALUES
(1, 'Favor', 'Voto a favor'),
(2, 'Contra', 'Voto en contra'),
(3, 'Abstención', 'Abstención de voto')
ON CONFLICT (id_tipo_voto) DO NOTHING;
