-- =====================================================
-- ISSUE #6: Motor de Reglas para Notas Condicionales
-- Sprint 3 - Semana 1 (Solo tablas base)
-- Motor: PostgreSQL (Supabase)
-- =====================================================

-- =====================================================
-- CATÁLOGOS
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_etapa_propuesta (
    id_etapa_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    orden INTEGER NOT NULL DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_etapa_propuesta_no_vacia
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_orden_etapa_propuesta
        CHECK (orden >= 0)
);

CREATE TABLE IF NOT EXISTS catalogo_origen_propuesta (
    id_origen_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    codigo VARCHAR(20) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT chk_origen_propuesta_no_vacio
        CHECK (BTRIM(nombre) <> ''),

    CONSTRAINT chk_codigo_origen_no_vacio
        CHECK (BTRIM(codigo) <> '')
);

-- ====================
-- TABLAS
-- ====================

CREATE TABLE IF NOT EXISTS leyenda_nota_condicional (
    id_leyenda INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) UNIQUE NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    contenido TEXT NOT NULL,
    id_etapa_propuesta INTEGER,
    id_estado_propuesta INTEGER,
    id_origen_propuesta INTEGER,
    orden_por_defecto INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_leyenda_etapa
        FOREIGN KEY (id_etapa_propuesta)
        REFERENCES catalogo_etapa_propuesta(id_etapa_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT fk_leyenda_estado_propuesta
        FOREIGN KEY (id_estado_propuesta)
        REFERENCES catalogo_estado_propuesta(id_estado_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT fk_leyenda_origen
        FOREIGN KEY (id_origen_propuesta)
        REFERENCES catalogo_origen_propuesta(id_origen_propuesta)
        ON DELETE SET NULL,

    CONSTRAINT chk_codigo_leyenda_no_vacio
        CHECK (BTRIM(codigo) <> ''),

    CONSTRAINT chk_titulo_leyenda_no_vacio
        CHECK (BTRIM(titulo) <> ''),

    CONSTRAINT chk_contenido_leyenda_no_vacio
        CHECK (BTRIM(contenido) <> '')
);

CREATE TABLE IF NOT EXISTS propuesta_leyenda (
    id_propuesta_leyenda INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propuesta INTEGER NOT NULL,
    id_leyenda INTEGER NOT NULL,
    orden_aparicion INTEGER DEFAULT 0,
    fecha_aplicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_propuesta_leyenda_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE CASCADE,

    CONSTRAINT fk_propuesta_leyenda_leyenda
        FOREIGN KEY (id_leyenda)
        REFERENCES leyenda_nota_condicional(id_leyenda)
        ON DELETE RESTRICT,

    CONSTRAINT uq_propuesta_leyenda
        UNIQUE (id_propuesta, id_leyenda),

    CONSTRAINT chk_orden_propuesta_leyenda
        CHECK (orden_aparicion >= 0)
);

ALTER TABLE propuesta
    ADD COLUMN IF NOT EXISTS id_origen_propuesta INTEGER,
    ADD COLUMN IF NOT EXISTS id_etapa_propuesta INTEGER,
    ADD COLUMN IF NOT EXISTS id_propuesta_base INTEGER,
    ADD COLUMN IF NOT EXISTS numero_resolucion VARCHAR(50),
    ADD COLUMN IF NOT EXISTS fecha_aprobacion DATE;

ALTER TABLE propuesta
    ADD CONSTRAINT fk_propuesta_origen
        FOREIGN KEY (id_origen_propuesta)
        REFERENCES catalogo_origen_propuesta(id_origen_propuesta)
        ON DELETE SET NULL;

ALTER TABLE propuesta
    ADD CONSTRAINT fk_propuesta_etapa
        FOREIGN KEY (id_etapa_propuesta)
        REFERENCES catalogo_etapa_propuesta(id_etapa_propuesta)
        ON DELETE SET NULL;

ALTER TABLE propuesta
    ADD CONSTRAINT fk_propuesta_base
        FOREIGN KEY (id_propuesta_base)
        REFERENCES propuesta(id_propuesta)
        ON DELETE SET NULL;

ALTER TABLE propuesta
    ADD CONSTRAINT chk_numero_resolucion_formato
        CHECK (
            numero_resolucion IS NULL
            OR numero_resolucion ~ '^AIR-RES-[0-9]{3}-[0-9]{4}$'
        );

-- Índices
CREATE INDEX IF NOT EXISTS idx_propuesta_origen
ON propuesta(id_origen_propuesta);

CREATE INDEX IF NOT EXISTS idx_propuesta_etapa
ON propuesta(id_etapa_propuesta);

CREATE INDEX IF NOT EXISTS idx_propuesta_base
ON propuesta(id_propuesta_base);

CREATE INDEX IF NOT EXISTS idx_propuesta_resolucion
ON propuesta(numero_resolucion);

CREATE INDEX IF NOT EXISTS idx_leyenda_origen
ON leyenda_nota_condicional(id_origen_propuesta);

CREATE INDEX IF NOT EXISTS idx_leyenda_etapa
ON leyenda_nota_condicional(id_etapa_propuesta);

CREATE INDEX IF NOT EXISTS idx_leyenda_estado
ON leyenda_nota_condicional(id_estado_propuesta);

CREATE INDEX IF NOT EXISTS idx_propuesta_leyenda_propuesta
ON propuesta_leyenda(id_propuesta);

-- =====================================================
-- DATOS INICIALES
-- =====================================================

INSERT INTO catalogo_etapa_propuesta
(id_etapa_propuesta, nombre, descripcion, orden)
VALUES
(1, 'Procedencia', 'Etapa inicial de recepción y validación de procedencia', 1),
(2, 'Análisis', 'Etapa de análisis técnico o de comisión', 2),
(3, 'Aprobación', 'Etapa de votación en el pleno', 3),
(4, 'Implementación', 'Etapa de ejecución o comunicación del acuerdo', 4)
ON CONFLICT (id_etapa_propuesta) DO NOTHING;

INSERT INTO catalogo_origen_propuesta
(id_origen_propuesta, nombre, codigo, descripcion)
VALUES
(1, 'Consejo Institucional', 'CI', 'Propuestas originadas por el Consejo Institucional'),
(2, '10% Asambleístas', '10P', 'Propuestas presentadas por al menos el 10% de los asambleístas'),
(3, 'Rectoría', 'REC', 'Propuestas originadas por la Rectoría'),
(4, 'Comisión Especial', 'COM', 'Propuestas originadas por una comisión especial')
ON CONFLICT (id_origen_propuesta) DO NOTHING;

INSERT INTO leyenda_nota_condicional
(id_leyenda, codigo, titulo, contenido, id_origen_propuesta, orden_por_defecto)
VALUES
(1, 'LEG-CI-001',
 'Nota de Procedencia - Consejo Institucional',
 'La Secretaría de la AIR no dispone de registros de asistencia detallados para las propuestas en etapa de procedencia originadas por el Consejo Institucional.',
 1,
 1),
(2, 'LEG-10P-001',
 'Nota de Procedencia - 10% Asambleístas',
 'Conforme al Estatuto Orgánico, las propuestas presentadas por al menos el 10% de los asambleístas se certifican según la recepción formal de la moción y los registros disponibles.',
 2,
 2),
(3, 'LEG-REC-001',
 'Nota de Recepción General',
 'El presente documento certifica la participación del asambleísta según los registros históricos de la Secretaría de la AIR.',
 NULL,
 99)
ON CONFLICT (id_leyenda) DO NOTHING;

-- ============================
-- FUNCIONES Y TRIGGERS
-- ============================
CREATE OR REPLACE FUNCTION fn_aplicar_leyendas_propuesta()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO propuesta_leyenda (
        id_propuesta,
        id_leyenda,
        orden_aparicion
    )
    SELECT
        NEW.id_propuesta,
        l.id_leyenda,
        l.orden_por_defecto
    FROM leyenda_nota_condicional l
    WHERE l.activo = TRUE
      AND (
            l.id_origen_propuesta IS NULL
            OR l.id_origen_propuesta = NEW.id_origen_propuesta
          )
      AND (
            l.id_etapa_propuesta IS NULL
            OR l.id_etapa_propuesta = NEW.id_etapa_propuesta
          )
      AND (
            l.id_estado_propuesta IS NULL
            OR l.id_estado_propuesta = NEW.id_estado_propuesta
          )
    ON CONFLICT (id_propuesta, id_leyenda) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_aplicar_leyendas_propuesta
AFTER INSERT OR UPDATE OF id_origen_propuesta, id_etapa_propuesta, id_estado_propuesta ON propuesta
FOR EACH ROW
EXECUTE FUNCTION fn_aplicar_leyendas_propuesta();

-- =========================
-- VISTAS
-- =========================

CREATE OR REPLACE VIEW v_leyendas_propuesta AS
SELECT
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    o.nombre AS origen_propuesta,
    e.nombre AS etapa_propuesta,
    ep.nombre AS estado_propuesta,
    l.codigo,
    l.titulo AS titulo_leyenda,
    l.contenido,
    pl.orden_aparicion
FROM propuesta_leyenda pl
JOIN propuesta p ON pl.id_propuesta = p.id_propuesta
JOIN leyenda_nota_condicional l ON pl.id_leyenda = l.id_leyenda
LEFT JOIN catalogo_origen_propuesta o ON p.id_origen_propuesta = o.id_origen_propuesta
LEFT JOIN catalogo_etapa_propuesta e ON p.id_etapa_propuesta = e.id_etapa_propuesta
LEFT JOIN catalogo_estado_propuesta ep ON p.id_estado_propuesta = ep.id_estado_propuesta;

CREATE OR REPLACE VIEW v_compilador_normativo_vigente AS
SELECT
    r.id_reglamento,
    r.nombre_normativa,
    r.sigla,
    en.id_elemento,
    en.id_elemento_padre,
    nr.nombre AS nivel,
    en.numero_etiqueta,
    en.contenido_texto,
    en.orden,
    en.fecha_inicio_vigencia,
    en.fecha_fin_vigencia,
    ev.nombre AS estado_vigencia
FROM elemento_normativo en
JOIN reglamento r ON en.id_reglamento = r.id_reglamento
JOIN catalogo_nivel_reglamento nr ON en.id_nivel_reglamento = nr.id_nivel_reglamento
JOIN catalogo_estado_vigencia ev ON en.id_estado_vigencia = ev.id_estado_vigencia
WHERE en.fecha_fin_vigencia IS NULL
  AND ev.nombre = 'Vigente';

CREATE OR REPLACE VIEW v_arbol_normativo AS
WITH RECURSIVE arbol AS (
    SELECT
        en.id_elemento,
        en.id_reglamento,
        en.id_elemento_padre,
        en.numero_etiqueta,
        en.contenido_texto,
        en.orden,
        1 AS profundidad,
        en.numero_etiqueta::TEXT AS ruta
    FROM elemento_normativo en
    WHERE en.id_elemento_padre IS NULL

    UNION ALL

    SELECT
        hijo.id_elemento,
        hijo.id_reglamento,
        hijo.id_elemento_padre,
        hijo.numero_etiqueta,
        hijo.contenido_texto,
        hijo.orden,
        padre.profundidad + 1,
        padre.ruta || ' > ' || hijo.numero_etiqueta
    FROM elemento_normativo hijo
    JOIN arbol padre ON hijo.id_elemento_padre = padre.id_elemento
)
SELECT
    a.*,
    r.nombre_normativa
FROM arbol a
JOIN reglamento r ON a.id_reglamento = r.id_reglamento;


-- =====================================================
-- FIN - ISSUE #6
-- =====================================================
