-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 7 - Gestión de Comisiones, Propuestas y Proponentes
-- Depende de: asambleista, sys_usuario, elemento_normativo
-- Motor: Supabase / PostgreSQL
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-- =====================================================
-- 1. CATÁLOGOS
-- =====================================================

CREATE TABLE IF NOT EXISTS catalogo_estado_propuesta (
    id_estado_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_estado_propuesta_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_propuesta (
    id_tipo_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    leyenda_legal TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_tipo_propuesta_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_comision (
    id_tipo_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_tipo_comision_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_rol_comision (
    id_rol_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_rol_comision_no_vacio CHECK (BTRIM(nombre_rol) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_tramite (
    id_tipo_tramite INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_tipo_tramite_no_vacio CHECK (BTRIM(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS catalogo_estado_asistencia (
    id_estado_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_estado_asistencia_no_vacio CHECK (BTRIM(nombre) <> '')
);

-- =====================================================
-- 2. PROPUESTAS
-- =====================================================

CREATE TABLE IF NOT EXISTS propuesta (
    id_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_propuesta VARCHAR(12) UNIQUE NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    id_tipo_propuesta INTEGER NOT NULL,
    id_estado_propuesta INTEGER NOT NULL,
    id_elemento_normativo INTEGER,
    fecha_presentacion DATE NOT NULL DEFAULT CURRENT_DATE,
    id_usuario_registro INTEGER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_propuesta_tipo
        FOREIGN KEY (id_tipo_propuesta)
        REFERENCES catalogo_tipo_propuesta(id_tipo_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_propuesta_estado
        FOREIGN KEY (id_estado_propuesta)
        REFERENCES catalogo_estado_propuesta(id_estado_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_propuesta_elemento
        FOREIGN KEY (id_elemento_normativo)
        REFERENCES elemento_normativo(id_elemento)
        ON DELETE SET NULL,

    CONSTRAINT fk_propuesta_usuario
        FOREIGN KEY (id_usuario_registro)
        REFERENCES sys_usuario(id_usuario)
        ON DELETE SET NULL,

    -- Formato: AIR-XXX-YYYY
    CONSTRAINT chk_numero_propuesta_formato
        CHECK (numero_propuesta ~ '^AIR-[0-9]{3}-[0-9]{4}$'),

    CONSTRAINT chk_titulo_propuesta_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

CREATE TABLE IF NOT EXISTS proponente_propuesta (
    id_proponente_propuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propuesta INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    rol_proponente VARCHAR(50) DEFAULT 'Proponente',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_proponente_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE CASCADE,

    CONSTRAINT fk_proponente_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT uq_proponente_propuesta
        UNIQUE (id_propuesta, id_asambleista)
);

-- =====================================================
-- 3. COMISIONES
-- =====================================================

CREATE TABLE IF NOT EXISTS comision (
    id_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_comision INTEGER NOT NULL,
    nombre_comision VARCHAR(150) NOT NULL,
    objeto TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_comision_tipo
        FOREIGN KEY (id_tipo_comision)
        REFERENCES catalogo_tipo_comision(id_tipo_comision)
        ON DELETE RESTRICT,

    CONSTRAINT chk_nombre_comision_no_vacio
        CHECK (BTRIM(nombre_comision) <> '')
);

CREATE TABLE IF NOT EXISTS proposito_comision (
    id_proposito_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    id_propuesta INTEGER NOT NULL,
    texto TEXT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_proposito_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_proposito_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT chk_texto_proposito_no_vacio
        CHECK (BTRIM(texto) <> '')
);

-- =====================================================
-- 4. INTEGRANTES DE COMISIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS integrante_comision (
    id_integrante_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    id_rol_comision INTEGER NOT NULL,
    fecha_ingreso_nombramiento DATE NOT NULL,
    fecha_fin_nombramiento DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_integrante_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_integrante_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_integrante_rol
        FOREIGN KEY (id_rol_comision)
        REFERENCES catalogo_rol_comision(id_rol_comision)
        ON DELETE RESTRICT,

    CONSTRAINT chk_estado_integrante
        CHECK (estado IN ('Activo', 'Inactivo')),

    CONSTRAINT chk_fechas_integrante
        CHECK (
            fecha_fin_nombramiento IS NULL
            OR fecha_fin_nombramiento >= fecha_ingreso_nombramiento
        )
);

CREATE TABLE IF NOT EXISTS bitacora_integrante_comision (
    id_bitacora_integrante_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_integrante_comision INTEGER NOT NULL,
    id_comision INTEGER NOT NULL,
    id_asambleista INTEGER NOT NULL,
    id_rol_comision INTEGER NOT NULL,
    fecha_ingreso_nombramiento DATE NOT NULL,
    fecha_fin_nombramiento DATE,
    estado VARCHAR(20) NOT NULL,
    accion VARCHAR(20) NOT NULL,
    fecha_bitacora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bitacora_integrante
        FOREIGN KEY (id_integrante_comision)
        REFERENCES integrante_comision(id_integrante_comision)
        ON DELETE CASCADE
);

-- =====================================================
-- 5. SESIONES DE COMISIÓN Y AGENDA
-- =====================================================

CREATE TABLE IF NOT EXISTS sesion_comision (
    id_sesion_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    observaciones TEXT,

    CONSTRAINT fk_sesion_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS punto_agenda_sesion_comision (
    id_punto_agenda_sesion_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion_comision INTEGER NOT NULL,
    id_proposito_comision INTEGER NOT NULL,
    id_tipo_tramite INTEGER NOT NULL,
    orden INTEGER NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,

    CONSTRAINT fk_punto_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_punto_proposito
        FOREIGN KEY (id_proposito_comision)
        REFERENCES proposito_comision(id_proposito_comision)
        ON DELETE RESTRICT,

    CONSTRAINT fk_punto_tipo_tramite
        FOREIGN KEY (id_tipo_tramite)
        REFERENCES catalogo_tipo_tramite(id_tipo_tramite)
        ON DELETE RESTRICT,

    CONSTRAINT uq_orden_sesion_comision
        UNIQUE (id_sesion_comision, orden),

    CONSTRAINT chk_orden_punto_comision
        CHECK (orden > 0),

    CONSTRAINT chk_titulo_punto_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

-- =====================================================
-- 6. INFORMES DEL DIRECTORIO Y JUSTIFICACIÓN LEGAL
-- =====================================================

CREATE TABLE IF NOT EXISTS informe_directorio (
    id_informe INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comision INTEGER NOT NULL,
    id_propuesta INTEGER NOT NULL,
    id_sesion_comision INTEGER,
    titulo VARCHAR(200) NOT NULL,
    recomendacion TEXT,
    fecha_presentacion DATE,

    CONSTRAINT fk_informe_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE RESTRICT,

    CONSTRAINT fk_informe_propuesta
        FOREIGN KEY (id_propuesta)
        REFERENCES propuesta(id_propuesta)
        ON DELETE RESTRICT,

    CONSTRAINT fk_informe_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE SET NULL,

    CONSTRAINT chk_titulo_informe_no_vacio
        CHECK (BTRIM(titulo) <> '')
);

CREATE TABLE IF NOT EXISTS justificacion_legal (
    id_argumento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    es_considerando BOOLEAN NOT NULL,
    contenido TEXT NOT NULL,

    CONSTRAINT chk_contenido_argumento_no_vacio
        CHECK (BTRIM(contenido) <> '')
);

CREATE TABLE IF NOT EXISTS justificaciones_por_informe (
    id_informe INTEGER NOT NULL,
    id_argumento INTEGER NOT NULL,
    orden_aparicion INTEGER NOT NULL,

    PRIMARY KEY (id_informe, id_argumento),

    CONSTRAINT fk_justificacion_informe
        FOREIGN KEY (id_informe)
        REFERENCES informe_directorio(id_informe)
        ON DELETE CASCADE,

    CONSTRAINT fk_justificacion_argumento
        FOREIGN KEY (id_argumento)
        REFERENCES justificacion_legal(id_argumento)
        ON DELETE RESTRICT,

    CONSTRAINT chk_orden_justificacion
        CHECK (orden_aparicion > 0),

    CONSTRAINT uq_orden_justificacion_informe
        UNIQUE (id_informe, orden_aparicion)
);

-- =====================================================
-- 7. ASISTENCIA A SESIONES DE COMISIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS asistencia_sesion_comision (
    id_asistencia_comision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asambleista INTEGER NOT NULL,
    id_sesion_comision INTEGER NOT NULL,
    id_comision INTEGER NOT NULL,
    id_estado_asistencia INTEGER NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asistencia_comision_asambleista
        FOREIGN KEY (id_asambleista)
        REFERENCES asambleista(id_asambleista)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asistencia_sesion_comision
        FOREIGN KEY (id_sesion_comision)
        REFERENCES sesion_comision(id_sesion_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_comision
        FOREIGN KEY (id_comision)
        REFERENCES comision(id_comision)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_estado
        FOREIGN KEY (id_estado_asistencia)
        REFERENCES catalogo_estado_asistencia(id_estado_asistencia)
        ON DELETE RESTRICT,

    CONSTRAINT uq_asistencia_comision
        UNIQUE (id_asambleista, id_sesion_comision)
);

-- =====================================================
-- 8. ÍNDICES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_propuesta_numero ON propuesta(numero_propuesta);
CREATE INDEX IF NOT EXISTS idx_propuesta_estado ON propuesta(id_estado_propuesta);
CREATE INDEX IF NOT EXISTS idx_propuesta_tipo ON propuesta(id_tipo_propuesta);
CREATE INDEX IF NOT EXISTS idx_proponente_propuesta ON proponente_propuesta(id_propuesta);
CREATE INDEX IF NOT EXISTS idx_proponente_asambleista ON proponente_propuesta(id_asambleista);

CREATE INDEX IF NOT EXISTS idx_proposito_comision ON proposito_comision(id_comision);
CREATE INDEX IF NOT EXISTS idx_proposito_propuesta ON proposito_comision(id_propuesta);

CREATE INDEX IF NOT EXISTS idx_integrante_comision ON integrante_comision(id_comision);
CREATE INDEX IF NOT EXISTS idx_integrante_asambleista ON integrante_comision(id_asambleista);
CREATE INDEX IF NOT EXISTS idx_integrante_fechas ON integrante_comision(fecha_ingreso_nombramiento, fecha_fin_nombramiento);

CREATE INDEX IF NOT EXISTS idx_sesion_comision ON sesion_comision(id_comision);
CREATE INDEX IF NOT EXISTS idx_sesion_comision_fecha ON sesion_comision(fecha_hora);

CREATE INDEX IF NOT EXISTS idx_informe_comision ON informe_directorio(id_comision);
CREATE INDEX IF NOT EXISTS idx_informe_propuesta ON informe_directorio(id_propuesta);

CREATE INDEX IF NOT EXISTS idx_asistencia_comision_sesion ON asistencia_sesion_comision(id_sesion_comision);
CREATE INDEX IF NOT EXISTS idx_asistencia_comision_asambleista ON asistencia_sesion_comision(id_asambleista);

-- =====================================================
-- 9. FUNCIONES Y TRIGGERS
-- =====================================================

CREATE OR REPLACE FUNCTION fn_validar_traslape_integrante_comision()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'Activo' THEN
        IF EXISTS (
            SELECT 1
            FROM integrante_comision ic
            WHERE ic.id_comision = NEW.id_comision
              AND ic.id_asambleista = NEW.id_asambleista
              AND ic.estado = 'Activo'
              AND ic.id_integrante_comision <> COALESCE(NEW.id_integrante_comision, -1)
              AND NEW.fecha_ingreso_nombramiento <= COALESCE(ic.fecha_fin_nombramiento, DATE '9999-12-31')
              AND COALESCE(NEW.fecha_fin_nombramiento, DATE '9999-12-31') >= ic.fecha_ingreso_nombramiento
        ) THEN
            RAISE EXCEPTION 'El asambleísta ya tiene un nombramiento activo en esa comisión durante ese periodo.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_bitacora_integrante_comision()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO bitacora_integrante_comision (
        id_integrante_comision,
        id_comision,
        id_asambleista,
        id_rol_comision,
        fecha_ingreso_nombramiento,
        fecha_fin_nombramiento,
        estado,
        accion
    )
    VALUES (
        COALESCE(NEW.id_integrante_comision, OLD.id_integrante_comision),
        COALESCE(NEW.id_comision, OLD.id_comision),
        COALESCE(NEW.id_asambleista, OLD.id_asambleista),
        COALESCE(NEW.id_rol_comision, OLD.id_rol_comision),
        COALESCE(NEW.fecha_ingreso_nombramiento, OLD.fecha_ingreso_nombramiento),
        COALESCE(NEW.fecha_fin_nombramiento, OLD.fecha_fin_nombramiento),
        COALESCE(NEW.estado, OLD.estado),
        TG_OP
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_punto_agenda_comision()
RETURNS TRIGGER AS $$
DECLARE
    v_comision_sesion INTEGER;
    v_comision_proposito INTEGER;
BEGIN
    SELECT id_comision
    INTO v_comision_sesion
    FROM sesion_comision
    WHERE id_sesion_comision = NEW.id_sesion_comision;

    SELECT id_comision
    INTO v_comision_proposito
    FROM proposito_comision
    WHERE id_proposito_comision = NEW.id_proposito_comision;

    IF v_comision_sesion <> v_comision_proposito THEN
        RAISE EXCEPTION 'El propósito de comisión no pertenece a la misma comisión de la sesión.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_informe_directorio()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM proposito_comision pc
        WHERE pc.id_comision = NEW.id_comision
          AND pc.id_propuesta = NEW.id_propuesta
    ) THEN
        RAISE EXCEPTION 'La propuesta del informe no está asociada a esa comisión.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_validar_asistencia_comision()
RETURNS TRIGGER AS $$
DECLARE
    v_comision_sesion INTEGER;
    v_fecha_sesion DATE;
BEGIN
    SELECT id_comision, fecha_hora::DATE
    INTO v_comision_sesion, v_fecha_sesion
    FROM sesion_comision
    WHERE id_sesion_comision = NEW.id_sesion_comision;

    IF v_comision_sesion <> NEW.id_comision THEN
        RAISE EXCEPTION 'La sesión indicada no pertenece a la comisión indicada.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM integrante_comision ic
        WHERE ic.id_comision = NEW.id_comision
          AND ic.id_asambleista = NEW.id_asambleista
          AND ic.estado = 'Activo'
          AND ic.fecha_ingreso_nombramiento <= v_fecha_sesion
          AND COALESCE(ic.fecha_fin_nombramiento, DATE '9999-12-31') >= v_fecha_sesion
    ) THEN
        RAISE EXCEPTION 'Solo se puede registrar asistencia de integrantes activos de la comisión en la fecha de la sesión.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_traslape_integrante_comision
BEFORE INSERT OR UPDATE ON integrante_comision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_traslape_integrante_comision();

CREATE TRIGGER tg_bitacora_integrante_comision
AFTER INSERT OR UPDATE OR DELETE ON integrante_comision
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_integrante_comision();

CREATE TRIGGER tg_validar_punto_agenda_comision
BEFORE INSERT OR UPDATE ON punto_agenda_sesion_comision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_punto_agenda_comision();

CREATE TRIGGER tg_validar_informe_directorio
BEFORE INSERT OR UPDATE ON informe_directorio
FOR EACH ROW
EXECUTE FUNCTION fn_validar_informe_directorio();

CREATE TRIGGER tg_validar_asistencia_comision
BEFORE INSERT OR UPDATE ON asistencia_sesion_comision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_asistencia_comision();

-- =====================================================
-- 10. VISTAS PARA CERTIFICACIONES
-- =====================================================

CREATE OR REPLACE VIEW v_proponentes_propuesta AS
SELECT
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    pp.rol_proponente
FROM proponente_propuesta pp
JOIN propuesta p ON pp.id_propuesta = p.id_propuesta
JOIN asambleista a ON pp.id_asambleista = a.id_asambleista;

CREATE OR REPLACE VIEW v_integrantes_comision AS
SELECT
    ic.id_integrante_comision,
    c.id_comision,
    c.nombre_comision,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    rc.nombre_rol,
    ic.fecha_ingreso_nombramiento,
    ic.fecha_fin_nombramiento,
    ic.estado
FROM integrante_comision ic
JOIN comision c ON ic.id_comision = c.id_comision
JOIN asambleista a ON ic.id_asambleista = a.id_asambleista
JOIN catalogo_rol_comision rc ON ic.id_rol_comision = rc.id_rol_comision;

CREATE OR REPLACE VIEW v_asistencia_comision AS
SELECT
    asc2.id_asistencia_comision,
    c.id_comision,
    c.nombre_comision,
    sc.id_sesion_comision,
    sc.fecha_hora,
    a.id_asambleista,
    a.cedula,
    a.nombre AS nombre_asambleista,
    ea.nombre AS estado_asistencia
FROM asistencia_sesion_comision asc2
JOIN sesion_comision sc ON asc2.id_sesion_comision = sc.id_sesion_comision
JOIN comision c ON asc2.id_comision = c.id_comision
JOIN asambleista a ON asc2.id_asambleista = a.id_asambleista
JOIN catalogo_estado_asistencia ea ON asc2.id_estado_asistencia = ea.id_estado_asistencia;

CREATE OR REPLACE VIEW v_informes_comision_certificacion AS
SELECT
    i.id_informe,
    c.id_comision,
    c.nombre_comision,
    p.id_propuesta,
    p.numero_propuesta,
    p.titulo AS titulo_propuesta,
    i.titulo AS titulo_informe,
    i.recomendacion,
    i.fecha_presentacion
FROM informe_directorio i
JOIN comision c ON i.id_comision = c.id_comision
JOIN propuesta p ON i.id_propuesta = p.id_propuesta;

-- =====================================================
-- 11. DATOS INICIALES
-- =====================================================

INSERT INTO catalogo_estado_propuesta
(id_estado_propuesta, nombre, descripcion)
VALUES
(1, 'Recibida', 'Propuesta recibida por la Secretaría de la AIR'),
(2, 'En análisis', 'Propuesta asignada a comisión para análisis técnico'),
(3, 'Dictaminada', 'Propuesta con informe de comisión'),
(4, 'Aprobada', 'Propuesta aprobada'),
(5, 'Rechazada', 'Propuesta rechazada')
ON CONFLICT (id_estado_propuesta) DO NOTHING;

INSERT INTO catalogo_tipo_propuesta
(id_tipo_propuesta, nombre, descripcion, leyenda_legal)
VALUES
(1, 'Etapa de Procedencia - Consejo Institucional', 'Propuesta enviada por el Consejo Institucional', 'La Secretaría de la AIR no dispone de registros de asistencia para esta etapa de procedencia.'),
(2, 'Etapa de Procedencia - 10% Asamblea', 'Propuesta presentada por al menos el 10% de la Asamblea', 'La propuesta fue presentada por el porcentaje requerido de miembros de la Asamblea.'),
(3, 'Propuesta conciliada', 'Propuesta construida por comisión o grupo de análisis', 'La propuesta conciliada registra proponentes e integrantes participantes.')
ON CONFLICT (id_tipo_propuesta) DO NOTHING;

INSERT INTO catalogo_tipo_comision
(id_tipo_comision, nombre, descripcion)
VALUES
(1, 'Comisión de análisis', 'Comisión encargada del estudio técnico de propuestas'),
(2, 'Comisión especial', 'Comisión temporal creada para un asunto específico')
ON CONFLICT (id_tipo_comision) DO NOTHING;

INSERT INTO catalogo_rol_comision
(id_rol_comision, nombre_rol, descripcion)
VALUES
(1, 'Coordinador', 'Coordina el trabajo de la comisión'),
(2, 'Secretario', 'Registra acuerdos y seguimiento'),
(3, 'Integrante', 'Participa en el análisis técnico')
ON CONFLICT (id_rol_comision) DO NOTHING;

INSERT INTO catalogo_tipo_tramite
(id_tipo_tramite, nombre, descripcion)
VALUES
(1, 'Lectura de acta', 'Revisión y aprobación del acta anterior'),
(2, 'Análisis de propuesta', 'Discusión técnica de una propuesta asignada'),
(3, 'Audiencia', 'Recepción de expertos, proponentes o sectores afectados'),
(4, 'Varios', 'Otros asuntos de la comisión')
ON CONFLICT (id_tipo_tramite) DO NOTHING;

INSERT INTO catalogo_estado_asistencia
(id_estado_asistencia, nombre, descripcion)
VALUES
(1, 'Presente', 'Asistió a la sesión'),
(2, 'Ausente', 'No asistió a la sesión'),
(3, 'Justificado', 'Ausencia justificada')
ON CONFLICT (id_estado_asistencia) DO NOTHING;
