-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-- ISSUE 12 - Motor de Votaciones
-- Autora: María Fernanda Vargas Guzmán
-- Depende de: sesion y votación (issue 5), asambleista (issue 9) y propuesta (issue 10) 
-- Complemento del Sistema de Votaciones
-- Semana 3
-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-- ................................................
-- Nuevos Catálogos (excepto catalogo_tipo_voto)
-- ................................................

CREATE TABLE IF NOT EXISTS catalogo_tipo_mayoria_requerida (
    id_tipo_mayoria_requerida INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    porcentaje_requerido NUMERIC(5,2) NOT NULL,
    descripcion TEXT,

    CONSTRAINT chk_porcentaje_mayoria
        CHECK (porcentaje_requerido > 0 AND porcentaje_requerido <= 100)
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_votacion (
    id_tipo_votacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_voto (
    id_tipo_voto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
);


-- .................................
-- Tabla resultado de votaciones
-- .................................

CREATE TABLE IF NOT EXISTS resultado_votacion (
    id_resultado_votacion BIGSERIAL PRIMARY KEY,
    id_votacion BIGINT NOT NULL UNIQUE,
    id_tipo_mayoria_requerida INTEGER NOT NULL,
    id_tipo_votacion INTEGER NOT NULL,

    total_presentes INTEGER NOT NULL DEFAULT 0,
    total_votos INTEGER NOT NULL DEFAULT 0,
    votos_favor INTEGER NOT NULL DEFAULT 0,
    votos_contra INTEGER NOT NULL DEFAULT 0,
    abstenciones INTEGER NOT NULL DEFAULT 0,
    porcentaje_aprobacion NUMERIC(5,2),
    resultado VARCHAR(30) NOT NULL,
    fecha_apertura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP,

    CONSTRAINT fk_resultado_votacion
        FOREIGN KEY (id_votacion)
        REFERENCES votacion(id_votacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_resultado_mayoria
        FOREIGN KEY (id_tipo_mayoria_requerida)
        REFERENCES catalogo_tipo_mayoria_requerida(id_tipo_mayoria_requerida)
        ON DELETE RESTRICT,

    CONSTRAINT fk_resultado_tipo_votacion
        FOREIGN KEY (id_tipo_votacion)
        REFERENCES catalogo_tipo_votacion(id_tipo_votacion)
        ON DELETE RESTRICT,

    CONSTRAINT chk_resultado
        CHECK (resultado IN ('Aprobada', 'Rechazada', 'Anulada')),

    CONSTRAINT chk_conteos_no_negativos
        CHECK (
            total_presentes >= 0 AND
            total_votos >= 0 AND
            votos_favor >= 0 AND
            votos_contra >= 0 AND
            abstenciones >= 0
        )
);
